### PR TITLE
Malteskoruppa constructor resolution

### LINKED ISSUE #1522: Cannot resolve constructor declaration from object creation expression with scope
Consider the following code:

```
class ConstructorCalls {

    void testNormalConstructor() {
        new OtherClass();
    }

    void testInnerClassConstructor() {
        OtherClass oc = new OtherClass();
        oc.new InnerClass();
    }
}

class OtherClass {

    OtherClass() {}

    class InnerClass {

        InnerClass() {}
    }
}
```

Calling `resolveInvokedConstructor()` on the object creation expression `new OtherClass()` works great! :smiley: 

However, calling `resolvedInvokedConstructor()` on the object creation expression `oc.new InnerClass()` throws an `UnsolvedSymbolException`. :disappointed: 

It would appear that the symbol solver cannot cope with object creation expressions that have a scope. Is that correct?

A pull request with corresponding tests is incoming.

### PR DESCRIPTION
**Pull request by ftomassetti**
Fixes #1522

### CODE REVIEW

**Comment by malteskoruppa** [comment]
Wow, that was fast! :-)

Ok, I think I understand what you did there. You essentially created an `ObjectCreationContext` which is able to resolve qualified object creation expressions by resolving the type of the scope, checking that this resolved type is a reference type, and then searching for the inner class within that reference type. It gives me an idea how resolving expressions works and what contexts are good for. Thank you very much!

One of the main problems with starting to understand the symbol solver is that the source code does not have a lot of documentation, unfortunately, so looking at individual commits where you know what problem they solve helps.

Side note: It looks like you updated the `javaparser-core-testing.iml` with some duplicate entries. It probably doesn't hurt but it's redundant. Not sure why your IDE did that. If you're using IntelliJ, you can probably cause IntelliJ to remove the duplicate entries again by right-clicking on `javaparser [javaparser-parent]` folder at the very top of the project window, then selecting _Maven -> Reimport_.

**Comment by matozoid** [comment]
I'll merge when the intellij config is fixed (or until release time - then I'll fix it myself ;-) )

I'm on holiday for the weekend by the way, so release will be next week.

**Comment by malteskoruppa** [comment]
> I'm on holiday for the weekend by the way, so release will be next week.

Have a good time! :-)

**Comment by matozoid** [comment]
Thanks @malteskoruppa !

**Comment by matozoid** [comment]
Well, there's still time for a weekend release.

**Pull request merged**
