### PR TITLE
Store path of source file on CompilationUnit

### PR DESCRIPTION
**Pull request by matozoid**
See #842 

It's a bit of a simplistic implementation. I could have stored the location of files loaded using a classloader for example, but I'm assuming that users who want that information have a very specific use case that they can build themselves.

`SourceRoot` has minor breakage: instead of a map of `path`->`ParseResult`, you now get a list of `ParseResult`. The `CompilationUnit` in the result has the path already.

This makes me wonder if the path shouldn't be stored in the `ParseResult`. Does anybody have a suggestion?

### CODE REVIEW

**Comment by DeepSnowNeeL** [comment]
I think compilation unit is better to store the path, so it opens up things
like compilationUnit.save() , which would be nonsense to do on a "parse
result"

**Comment by matozoid** [comment]
Oh right, I could put save on there as well.

**Comment by ftomassetti** [comment]
What is the status of this one? Do you need a review? Are you still working on this one?

**Comment by matozoid** [comment]
Yes, I'm cleaning up smaller stuff for now, but I'll get back to this one soon.

One thing I was pondering is whether you should be able to ask the compilation unit for the source directory, and I think that's a good idea:

`file location = source directory + package + file name`

I had some doubt about if it is smart to use the `PackageDeclaration` to figure out the package, and I think it is. It should be correct almost always, and when it isn't a big exception is fitting.

This would make interoperability with `SourceRoot` a lot easier too.

**Pull request merged**
