### PR TITLE
Contribution guidelines updates

### PR DESCRIPTION
**Pull request by jeandersonbc**
As we discussed on Gitter, the contribution guidelines should be more clear about the development workflow. Here are my suggestions

### CODE REVIEW

**Comment by matozoid** [comment]
+1

**Comment by jeandersonbc** [comment]
Strange.... Do we have flaky tests? It doesn't make sense to have test failures.

**Comment by matozoid** [comment]
Appveyor has been broken for quite a while now - something is spuriously wrong on Windows...

**Comment by jeandersonbc** [comment]
Got it! We should register this in our issue tracker (ignore if someone already has filed an issue for this)

**Pull request merged**
