### PR TITLE
Issue 1888 - path equality -> file equality (attempt 2)

### PR DESCRIPTION
**Pull request by MysterAitch**
Changed from using `Path.equals` to `File.isSameFile`. See #1888. Also added null check (`Path.equals` would previously have simply returned false, while `Files.isSameFile` throws NPE).

(Attempt 2 as #2040 was getting extremely messy/unwieldy).

### CODE REVIEW

**Comment by MysterAitch** [comment]
Phew, both checks passed. That was much harder work than it likely should have been - sorry for the noise!! :grimacing: :D 

I still think that `SourceRoot` should also receive the same fix, and the null check seems redundant given that if a null is passed to `path` then it'll be flagged higher up, and `dir` will always have a value as it is the current 'focus' of the visitor. 

I'll leave that alone and move on for now though!

**Comment by matozoid** [comment]
I'm kind of warming up to the idea of fixing SourceRoot now :-)

But let's merge this one.

**Comment by pkoziol** [comment]
Is there a reason why `SymbolSolverCollectionStrategy` was skipped in this PR (it was modified in #2040)?

I'm asking, because I replaced `ParserCollectionStrategy` with `SymbolSolverCollectionStrategy` and my program broke. Apparently `ParserCollectionStrategy` works for relative paths and `SymbolSolverCollectionStrategy` doesn't. If `SymbolSolverCollectionStrategy` would use `Files.isSameFile` everything would be OK.

**Comment by matozoid** [comment]
I don't think there is a reason. Would you mind making a PR for this change?

**Pull request merged**
