### PR TITLE
[TESTCASES] Mismatch between VoidVisitor and node.findAll

### LINKED ISSUE #2366: Symbol Solver unable to resolve nested classes
Symbol Solver unable to resolve nested classes in object creation expressions.

Java Parser Version: 3.14.13

If we try to resolveObjectCreationExpr for the following code

```java
public class Test
{
   public class InnerTest
   {
       public InnerTest(int i) {}
   }
    
   public Test() {
   }

   public static void main( String[] args ) { 
       new Test().new InnerTest();
   }
}
```
with the following code (codeSource is String with the above code)

```java
CombinedTypeSolver combinedSolver = new CombinedTypeSolver(new ReflectionTypeSolver());	    

ParserConfiguration pc = new ParserConfiguration()
    	                        .setSymbolResolver(new JavaSymbolSolver(combinedSolver))
    	                        .setLanguageLevel(LanguageLevel.JAVA_8);			

StaticJavaParser.setConfiguration(pc);

new VoidVisitorAdapter<Object>() {
    @Override
    public void visit(ObjectCreationExpr exp, Object arg) {
        System.out.println(exp.resolve().getSignature());
    }            
}.visit(StaticJavaParser.parse(codeSource), null);
```

causes exception in line 156 of com.github.javaparser.ast.CompilationUnit.JavaSymbolSolver class.

Interestingly, if inner class constructor is removed Symbol Solver is able to resolve inner class object creation expression, but not outer class object creation expression.

If you try to parenthesize outer class object creation expression:  ```(new Test()).new InnerTest();```  Symbol Solver simply hangs.

### PR DESCRIPTION
**Pull request by SimonBaars**
This is a bunch of test cases used to investigate #2366 and #2370. One of the test cases does not yet pass, accounting for the problem outlined in issue #2370.

Closes #2366

### CODE REVIEW

**Comment by matozoid** [comment]
How odd. What do you get when you use YamlPrinter on the test case?

**Comment by SimonBaars** [comment]
This is the result:
```
---
root(Type=CompilationUnit): 
    types: 
        - type(Type=ClassOrInterfaceDeclaration): 
            isInterface: "false"
            name(Type=SimpleName): 
                identifier: "Test"
            members: 
                - member(Type=ClassOrInterfaceDeclaration): 
                    isInterface: "false"
                    name(Type=SimpleName): 
                        identifier: "InnerTest"
                    members: 
                        - member(Type=ConstructorDeclaration): 
                            body(Type=BlockStmt): 
                            name(Type=SimpleName): 
                                identifier: "InnerTest"
                            modifiers: 
                                - modifier(Type=Modifier): 
                                    keyword: "PUBLIC"
                    modifiers: 
                        - modifier(Type=Modifier): 
                            keyword: "PUBLIC"
                - member(Type=ConstructorDeclaration): 
                    body(Type=BlockStmt): 
                    name(Type=SimpleName): 
                        identifier: "Test"
                    modifiers: 
                        - modifier(Type=Modifier): 
                            keyword: "PUBLIC"
                - member(Type=MethodDeclaration): 
                    body(Type=BlockStmt): 
                        statements: 
                            - statement(Type=ExpressionStmt): 
                                expression(Type=ObjectCreationExpr): 
                                    scope(Type=ObjectCreationExpr): 
                                        type(Type=ClassOrInterfaceType): 
                                            name(Type=SimpleName): 
                                                identifier: "Test"
                                    type(Type=ClassOrInterfaceType): 
                                        name(Type=SimpleName): 
                                            identifier: "InnerTest"
                    type(Type=VoidType): 
                    name(Type=SimpleName): 
                        identifier: "main"
                    modifiers: 
                        - modifier(Type=Modifier): 
                            keyword: "PUBLIC"
                        - modifier(Type=Modifier): 
                            keyword: "STATIC"
                    parameters: 
                        - parameter(Type=Parameter): 
                            isVarArgs: "false"
                            name(Type=SimpleName): 
                                identifier: "args"
                            type(Type=ArrayType): 
                                origin: "TYPE"
                                componentType(Type=ClassOrInterfaceType): 
                                    name(Type=SimpleName): 
                                        identifier: "String"
            modifiers: 
                - modifier(Type=Modifier): 
                    keyword: "PUBLIC"
...
```
In this output it seems like there are two `ObjectCreationExpr`, different from what the `VoidVisitorAdapter` walks.

**Comment by matozoid** [comment]
Ah, I should have noticed right away: you forgot to call super in the visit method. (I was staring at the findall test.)

**Comment by SimonBaars** [comment]
Ah, thanks. I will redirect this message to the guy who originally filed
this issue.

**Comment by matozoid** [comment]
Do you think we should merge this?

**Comment by SimonBaars** [comment]
I think so yes because I think they are valuable testcases. I moved the test cases to appropriate (descriptive) places.

**Comment by matozoid** [comment]
Here they go :-)

**Pull request merged**
