### PR TITLE
Use a singleton javassist classpool to fix issue #1771 and all relate…

### LINKED ISSUE #1771: fail if a type is defined in a JAR, but implements an interface defined in another JAR
See #362 and #1851

### PR DESCRIPTION
**Pull request by jlerbsc**
…d issues  #362 and #1851 and revert a part of the PR ##3126 that is not compatible with the classpool singleton

Fixes #1771.

### CODE REVIEW

**Comment by maartenc** [comment]
@jlerbsc , @MysterAitch 

I don't think this is a good fix, although it will probably solve the mentioned issues, it will create new problems.

For instance: I have a use case where I use JavaParser to check the dependencies of multiple Java libraries.
For each library a 'root typeresolver' is created, and external jars are added to this resolver using the javassist typesolver.
When one 'root typesolver' can see classes from another one, strange things can happen.

It's not a good idea to 'leak' javassist classes accross the boundaries of such a typesolver. Since it is static now, this will be the case. Please revert and change the scope of the javasisst classes to the scope of the type solver.

**Comment by maartenc** [comment]
See also my comment in https://github.com/javaparser/javaparser/issues/2762

**Comment by MysterAitch** [comment]
Just commented within #2762 

There are a lot of threads with similar topics, is there an obvious choice available where we can direct discussion to a single issue?

**Comment by jlerbsc** [comment]
> It's not a good idea to 'leak' javassist classes accross the boundaries of such a typesolver. Since it is static now, this will be the case. Please revert and change the scope of the javasisst classes to the scope of the type solver.

@maartenc there are many issues that are related to this problem. Do you have another solution to offer these users who have potentially been blocked for several months or even years.

> When one 'root typesolver' can see classes from another one, strange things can happen.

Can you clarify the "strange things" and propose a test case so that we can work on them as well?

**Comment by maartenc** [comment]
For instance: a problem can be like this:

```
CombinedTypeSolver solver1 = new CombinedTypeSolver();
solver1.add(new JarTypeSolver("guava-12.0.jar"));
solver1.add(new ReflectionTypeSolver());

CombinedTypeSolver solver2 = new CombinedTypeSolver();
solver2.add(new JarTypeSolver("guava-13.0.jar"));
solver2.add(new ReflectionTypeSolver());
```

Which guava version will solver1 and solver2 use?
Will solver1 use 12.0 and solver2 use 13.0 ?
Will both use 12.0? Or both use 13.0? Or will it be a mix?

**Comment by maartenc** [comment]
Another easy solution is your first suggestion in #2762

**Pull request merged**
