### PR TITLE
Fix resolving methods with generic return types

### PR DESCRIPTION
**Pull request by maartenc**
Fix an issue with resolving generic return types.

Consider the example below, when resolving the `foo()` methodcall in the Bar class, the return type was not resolved to `String`, but was still `T`.

```
public class Foo <T> {
    public T foo() {
        return null;
    }
}

public class Bar extends Foo<String> {
    public void bar() {
        foo();
    }
}
```

### CODE REVIEW

**Comment by maartenc** [comment]
Hmz, I have broken some tests... I'll look into it...

**Comment by matozoid** [comment]
Hey @maartenc - how is this one going?

**Comment by maartenc** [comment]
Sorry, I didn't had much time yet

**Comment by matozoid** [comment]
Hey cool! Time to merge it.

**Pull request merged**
