### PR TITLE
Improvements to comments attribution

### PR DESCRIPTION
**Pull request by ftomassetti**
I create this pull request to discuss possible improvements to comments attributions. I added a couple of comments explaining why I expect certain results. If we agree that make sense I could document this logic.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Today I added some other commits to deal with issue #45 and issue #49

**Comment by ftomassetti** [comment]
I will leave the merge request open until the 28 of July, then if I will not get comments I will merge it.

**Comment by SmiddyPence** [comment]
Couldn't see any problems.

General gripe, not necessarily with this pull request is the untidiness of the tests; I think now we are adding more it is becoming more important.  

I think I prefer the convention of having the src used in tests in a separate file rather than inline Strings in the test code.  Especially for anything over a couple of line, potentially we can reuse some as well.  

The two files "TestCommentsParser" and "TestCommentsParsing" seem just to be two buckets with slightly different names. 

Some tests use Hamcrest matchers other don't.

What I assume is legacy test code, that uses main rather than JUnit.

Once this is merged I'm happy to take a pass over tidying it up. (Rather than just complaining about it!)

**Comment by ftomassetti** [comment]
I agree with all you said. I think one set of tests was meant to check if the comments parser could get all the comments (with right content and position) while the other one should check that comments are attributed correctly. Probably now it is just a mess with no logical division... so it would be great if you can put some order, maybe when tests will be in order we will be encouraged to writ more of them.
Thanks!

**Comment by ftomassetti** [comment]
Merged and opened issue #59 from the comment of @SmiddyPence

**Pull request merged**
