### PR TITLE
add missed parameter

### PR DESCRIPTION
**Pull request by izebit**
Maybe I am wrong, but it seems to me that there is a mistake here

### CODE REVIEW

**Comment by ftomassetti** [comment]
mmm... it seems suspicious indeed. Let's see what tests think about that

**Comment by matozoid** [comment]
+1

We should document that this is now the way to do symbol solving: https://github.com/javaparser/javasymbolsolver-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/MyAnalysis.java

**Comment by izebit** [comment]
Sorry, I don't quite follow you. Did I understand you correctly, that I had to write tests for this case?

**Comment by matozoid** [comment]
@izebit the test suite runs for every PR. It has passed as you can see from all the green :-)

**Comment by izebit** [comment]
@matozoid To be honest, I don't understand what you are talking about. I don't have much knowledge about  `java parser`. To my mind, your example isn't related to my case, and what should I do?

**Comment by matozoid** [comment]
@izebit we seem to be missing each other's points here. The PR is fine. Thank you for contributing!

**Pull request merged**
