### PR TITLE
fix line separators of selected test files

### LINKED ISSUE #4077: After building JavaParser (with tests) on MacOS multiple committed files are modified
When doing a `mvn clean install` of JavaParser on MacOS multiple committed files are modified:
Screenshot 2023-06-22 at 21 59 24

The difference is in the line endings: the files are committed with `"\r\n"` line endings, but after running the tests on MacOS the files have `"\n"` line endings.

Having those files modified is annoying when developing JavaParser code as one always have to rollback those changes or explicitly exclude those files before commiting changes.

_(From what I can tell the files are modified in the `SourceRootTest`, by the test methods `saveInCallback()` and `saveInCallbackParallelized()`.)_

### PR DESCRIPTION
**Pull request by abego**
to resolve https://github.com/javaparser/javaparser/issues/4077

as discussed here: https://github.com/javaparser/javaparser/pull/4078#issuecomment-1606043764

### CODE REVIEW

**Comment by jlerbsc** [comment]
It seems correct to me. Thank you for your contribution.

**Comment by jlerbsc** [comment]
After analysis, the cause of this problem comes mainly from the SourceRoot class which uses printing configuration parameters with default values. The default end-of-line character is system-specific (on Windows it's CRLF...). This only raises a problem when this class is asked to parse and save the result, which is done in particular by the SourceRootTest test class. In this case, ideally, one should use the end-of-line character used in the parsed file.

**Comment by abego** [comment]
> After analysis, the cause of this problem comes mainly from the SourceRoot class which uses printing configuration parameters with default values. The default end-of-line character is system-specific (on Windows it's CRLF...). This only raises a problem when this class is asked to parse and save the result, which is done in particular by the SourceRootTest test class. In this case, ideally, one should use the end-of-line character used in the parsed file.

That was also my analysis of the problem and my initial PR  (https://github.com/javaparser/javaparser/pull/4078/files) was exactly your suggestion "one should use the end-of-line character used in the parsed file.", i.e. use "\r\n" as the end-of-line character as that was the one used in the parsed files.

Anyhow, the current solution (store the files with "\n" in Git and let Git change it to the actual system-specific ending on checkout) does not require extra changes in the test code, hence in much simpler, so I would keep it.

**Comment by jlerbsc** [comment]
> Anyhow, the current solution (store the files with "\n" in Git and let Git change it to the actual system-specific ending on checkout) does not require extra changes in the test code, hence in much simpler, so I would keep it.

This solution doesn't work because the test class rewrites the classes after parsing them and it doesn't default to using the system end-of-line character. I noticed this problem after checking out the project and running the tests.

**Comment by jlerbsc** [comment]
> That was also my analysis of the problem and my initial PR (https://github.com/javaparser/javaparser/pull/4078/files) was exactly your suggestion "one should use the end-of-line character used in the parsed file.", i.e. use "\r\n" as the end-of-line character as that was the one used in the parsed files.

Indeed your first solution was correct.

**Pull request merged**
