### PR TITLE
Fix resolving overloaded methods of external types

### LINKED ISSUE #2667: org.json chaining method issue
Hello.
There is a problem with ReflectionTypeSolver and json lib:
```
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20140107</version>
        </dependency>
```
Code:
```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.HashSet;
import java.util.Set;

public class Parser {

    public static void main(String[] args) {

        String s =
                "import org.json.JSONObject;\n" +
                        "\n" +
                        "public class ChainingTest {\n" +
                        "\n" +
                        "    public static void main (String args[]) {\n" +
                        "        JSONObject jsonObject = new JSONObject();\n" +
                        "        jsonObject.put(\"k1\", 1).put(\"k2\", \"v2\");\n" +
                        "    }\n" +
                        "\n" +
                        "}\n";
        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        Set<MethodCallExpr> methodCallExpr = new HashSet<>(cu.findAll(MethodCallExpr.class));
        for (MethodCallExpr expr : methodCallExpr) {
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println("\t Solved : " + rd.getQualifiedSignature());
        }
    }
}

```
Exception:
```
Exception in thread "main" UnsolvedSymbolException{context='jsonObject.put("k1", 1).put("k2", "v2")', name='jsonObject.put("k1", 1)', cause='com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,boolean) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='boolean'}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,double) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='double'}]}. First declared in org.json.JSONObject'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:155)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:270)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:32)
Caused by: com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,boolean) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='boolean'}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,double) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='double'}]}. First declared in org.json.JSONObject
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicableUsage(MethodResolutionLogic.java:581)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.solveMethodAsUsage(ReflectionClassDeclaration.java:224)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:182)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:428)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:121)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:679)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:289)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 6 more
```

I'm not sure is this the parser bug, but the problem is disappear when methods are not chained:
```
public static void main (String args[]) {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("k1", 1);
        jsonObject.put("k2", "v2");
    }
```
Maybe someone can shed some light to this strange parser behavior.

### LINKED ISSUE #2684: JavaSymbolSolver is not able to solve "System" in "System.out.println()"
I suppose this is another instance of the same problem.
JSS 3.15.22

Test class:

```java
package test;

class Test {
    private void ioexc() throws java.io.IOException {
        System.out.println("Hello World");
    }
}
```

parser & type solver:

```java
ParserConfiguration pc = new ParserConfiguration();
pc.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
JavaParser jp = new JavaParser(pc);
ParseResult<CompilationUnit> result = jp.parse(
    new File("D:\\Projects\\java.jext\\jext.main\\src\\test\\Test.java")
);
CompilationUnit cu = result.getResult().get();
```

I try to solve all 'NameExpr' nodes

```java
cu.findAll(NameExpr.class)
            .forEach(ne -> {
                try {
                    System.out.println(ne.getName().asString());
                    ne.resolve();
                }
                catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            });
```

It is not able to solve the symbol "System" in "System.out.println()"
Reference: JLS [8..14] Chapter 6: "Names"

### PR DESCRIPTION
**Pull request by maartenc**
Fixes #2667.

### CODE REVIEW

**Comment by maartenc** [comment]
I like it when deleting code fixes issues :)

**Comment by maartenc** [comment]
I think this bug has also been fixed by merging #2675 into master.

**Comment by MysterAitch** [comment]
> 
> 
> I think this bug has also been fixed by merging #2675 into master.

Apologies if that's the case, I hadn't intended to step on your toes!

If nothing else, I would still like to merge this as you seem to have put together good tests incl. a jar :+1:

**Comment by maartenc** [comment]
yes if you could merge the test case that would be good.

In addition, perhaps you could remove this commented code from MethodeResolutionLocic.java? It was the root of the problem and PR #2675 did comment it out...

```
//            // If there's a match already, return true.
//            // (n.b. won't be true in the case of an array method parameter vs many arguments, or where type parameters are used).
//            // TODO: How can it be the case that we can confidently short-circuit the loop here..? e.g. void foo(String... s){} called with foo("a", "b", false, "c") would ignore the non-string value in the middle...
//            if (expectedArgumentType.describe().equals(actualArgumentType.describe())) {
//                return true;
//            }
```

**Comment by maartenc** [comment]
> Apologies if that's the case, I hadn't intended to step on your toes!

No problem at all!!! :-)

**Comment by MysterAitch** [comment]
> 
> 
> yes if you could merge the test case that would be good.
> 
> In addition, perhaps you could remove this commented code from MethodeResolutionLocic.java? It was the root of the problem and PR #2675 did comment it out...
> 
> ```
> //            // If there's a match already, return true.
> //            // (n.b. won't be true in the case of an array method parameter vs many arguments, or where type parameters are used).
> //            // TODO: How can it be the case that we can confidently short-circuit the loop here..? e.g. void foo(String... s){} called with foo("a", "b", false, "c") would ignore the non-string value in the middle...
> //            if (expectedArgumentType.describe().equals(actualArgumentType.describe())) {
> //                return true;
> //            }
> ```

Sure! 

Looks like this will happen by merging this PR :smile:

**Pull request merged**
