### PR TITLE
Upgrade to jbehave-junit-runner 2.0.0

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by matozoid** [comment]
Thanks! I was looking for the leading git repo for this plugin so I could star and follow it. Do you know which one it is?

**Comment by valfirst** [comment]
@matozoid , now it's https://github.com/valfirst/jbehave-junit-runner/ (the ownership was transferred recently)

**Comment by matozoid** [comment]
@valfirst cool, will you also fix the intellij plugin? :-D

**Comment by valfirst** [comment]
@matozoid, which one? there are some of them, I might take a look 😄

**Comment by matozoid** [comment]
@valfirst I can't find release notes. Is anything interesting fixed since 1.2.0? I'll pull it anyway, just curious.

**Comment by valfirst** [comment]
@matozoid , please take a look: https://github.com/valfirst/jbehave-junit-runner/releases

**Comment by matozoid** [comment]
Here's the one I have installed: https://github.com/witspirit/IntelliJBehave

... it breaks horribly when tests fail.

**Comment by valfirst** [comment]
> Here's the one I have installed: https://github.com/witspirit/IntelliJBehave
> ... it breaks horribly when tests fail.

So many plugins: https://plugins.jetbrains.com/category/23-jbehave/idea...

It looks like this one https://github.com/stefanschenk/IntelliJBehave is the latest release of forks of forks. I'll try to investigate and may be fix/update one of them.

In general I agree, there should be some official plugin supported and released by JBehave community

**Pull request merged**
