### PR TITLE
Fix #2404: IndexOutOfBoundsException for empty javadoc

### LINKED ISSUE #2404: Empty javadoc results in IndexOutOfBoundsException in JavadocParser
See https://github.com/revelc/impsort-maven-plugin/issues/16

Parsing of empty javadoc, eg:

    /**
    */
    public class SomeClass {
        List something = new ArrayList();
    }

Fails with IndexOutOfBoundsException

    Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck (ArrayList.java:653)
    at java.util.ArrayList.get (ArrayList.java:429)
    at com.github.javaparser.JavadocParser.cleanLines (JavadocParser.java:124)
    at com.github.javaparser.JavadocParser.parse (JavadocParser.java:50)

### PR DESCRIPTION
**Pull request by bedlaj**
Fixes #2404.

### CODE REVIEW

**Review by edefazio — APPROVED** [review]
Looks good, I can verify the problem does exist and this seems to fix it.
(sorry for my earlier post if you saw it before it got deleted...)

**Comment by matozoid** [comment]
Thanks! This will be in tonight's release.

**Comment by ctubbsii** [comment]
Will 3.15.4 be released to Maven Central with this fix soon?

**Comment by matozoid** [comment]
@ctubbsii looks like I forgot to press a few buttons. Doing it right now. It should be available somewhere today.

```
Last Synced: Wed Nov 06 07:08:30 GMT 2019
Last Sync Status: Successfully synced and closed repo.
```

**Comment by ctubbsii** [comment]
No problem. Thanks!

**Pull request merged**
