### PR TITLE
Issue 180: the end position of ArrayCreationExpr for primitive types is wrong

### PR DESCRIPTION
**Pull request by ftomassetti**
Correcting issue #180 as nicely suggested by @Legioth
Adding test to prevent regressions

### CODE REVIEW

**Comment by ftomassetti** [comment]
Any comment on this one?

**Comment by SmiddyPence** [comment]
Perhaps the name is not the best, but the intention of "SharedSteps" was to include more of the common aspects of loading classes etc.  Open to something more descript.

The `@Then` s I would suggest are more to do with ensuring the correctness of parsing scenarios. So ParsingSteps.

Also I would tend to group whens and thens together, we have a when right after some thens in this case.

Two of the `@Then` have contradicting parameter names `$line` and `column`.

**Comment by ftomassetti** [comment]
Thank you for your review. 
- I moved all but the first new step to ParsingSteps. I left `whenTheFollowingSourceIsParsedTrimmingSpace` in SharedSteps because it is a variant of `whenTheFollowingSourceIsParsed` which was already in SharedSteps. If you prefer that I move both to ParsingSteps I will do that.
- I moved the steps at the end of ParsingSteps so the only 'when' step is at the end of the file, all the others are 'then' steps. Do you prefer that I move the 'when' step at the top of ParsingSteps?
- I corrected the contradicting $line params

**Comment by SmiddyPence** [comment]
Sure makes, sense.

Personal preference would be the given-when-then, but we're nit picking here though ;-)

**Comment by ftomassetti** [comment]
Nothing agains nit picking :)
I reorder the steps and added comments to identify the blocks

**Comment by SmiddyPence** [comment]
Cool, closing.

**Pull request merged**
