### PR TITLE
Add a "github action" to mark version tags as releases

### PR DESCRIPTION
**Pull request by MysterAitch**
Adds a "github action" to trigger a github release (as opposed to tag) every time a tag is pushed with the specified pattern (currently `javaparser-parent-[0-9].*` as this matches the tags added by the maven release plugin).

The benefit here is that it should then trigger the release webhooks, thus triggering actions such as those in #2148 to recognise the pushed tags as a new release.

### CODE REVIEW

**Comment by MysterAitch** [comment]
I've been experimenting with this at https://github.com/MysterAitch/test-release-actions (feel free to have a play also!)

It looks like all tags that get pushed (e.g. if pushing three or four tags in one push) are processed, and it seems to treat annotated tags (to be generally avoided) and unannotated tags (preferred) equally.

Note `git push --follow-tags` is preferred (it'll only push annotated tags) over `git push --tags` (pushes all tags)

**Comment by matozoid** [comment]
This looks alright, but I can't see from what you're saying if this is ready to merge? When do tags get annotated?

**Comment by MysterAitch** [comment]
Apologies for the lack of clarity!!

The annotated tag comments were more a general "think aloud" about manually-added tags.

In JavaParser's case, the tags added and pushed (I believe) by the maven release plugin are sufficient to trigger this action.

**Comment by matozoid** [comment]
Here goes then! Thanks :-)

**Pull request merged**
