### PR TITLE
Improving Symbol-Solving of Method References

### PR DESCRIPTION
**Pull request by scootafew**
Improved how `MethodReferenceExpr`'s are resolved to `MethodUsage`'s to more closely align with how it is done for regular `MethodCallExpr`'s. Also added plenty of test cases to verify new behavior.

Please note: I've left two test cases disabled as they currently fail due to #2455. I believe the solution lies in modifying the grammar so that field accesses and name expressions are parsed as such in the scope of `MethodReferenceExpr`'s, rather than copying symbol solving logic from these to the method solving a `TypeExpr`.

### CODE REVIEW

**Comment by matozoid** [comment]
Awesome!

**Comment by matozoid** [comment]
Looks like there is a JDK-dependent test there. It's best to avoid solver tests that assume something about the contents of the JDK :-)

**Comment by scootafew** [comment]
Test failure:
```
MethodReferenceResolutionTest.superclassMethodOverridden:94 expected: <java.util.AbstractList.hashCode()> but was: <java.util.ArrayList.hashCode()>
```

I always love it when a test passes locally and then not on the build :D Makes it slightly harder to debug. Do you have any idea why behavior may be different to locally @matozoid ? Also considering that `ArrayList` itself doesn't override hashcode I'm scratching my head...

**Comment by scootafew** [comment]
Ahh we commented at the same time, I understand. Will fix!

**Comment by matozoid** [comment]
Thanks! I'll do a release on Sunday.

**Pull request merged**
