### PR TITLE
Implemented logic for getAllFields in Annotations

### LINKED ISSUE #3094: Unable to solve NameExpr in Annotation
I have the following class
```java
@interface Foo { 
    int a = 0; 
    int b = a; 
}
```
When i try to resolve the reference, it throws a UnsupportedOperationException. This happens because method `getAllFields` is not implemented `JavaParserAnnotationDeclaration` and according to issue https://github.com/javaparser/javaparser/issues/1837 annotations should not have fields. The problem gets confusing when the AST parses the annotation with a field declaration on it.

Should it be consider a problem with  `JavaParserAnnotationDeclaration` or with the parser?

#### AST from the example
graphviz

#### Stack trace
```
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserAnnotationDeclaration.getAllFields(JavaParserAnnotationDeclaration.java:68)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.hasField(ResolvedReferenceTypeDeclaration.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AnnotationDeclarationContext.solveSymbol(AnnotationDeclarationContext.java:53)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbol(Context.java:115)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:70)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:74)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:171)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:181)
	at com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:170)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:72)
```

#### Unit test
```java
@Test
void test() {
  StaticJavaParser.getConfiguration()
		.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

  String sourceCode = "@interface Foo { int a = 0; int b = a; }";

  CompilationUnit cu = StaticJavaParser.parse(sourceCode);

  Optional<NameExpr> nameExpr = cu.findFirst(NameExpr.class);
  assertTrue(nameExpr.isPresent());
  assertDoesNotThrow(nameExpr.get()::resolve);
}
```

### PR DESCRIPTION
**Pull request by 4everTheOne**
Fixes #3094.

### CODE REVIEW

**Comment by jlerbsc** [comment]
To be complete it would also be necessary to implement JavassistAnnotationDeclaration and ReflectionAnnotationDeclaration

**Comment by 4everTheOne** [comment]
Thank you for the warning. Now it should be completed.

**Comment by jlerbsc** [comment]
@MysterAitch if you are agree with this PR perhaps you can merge it?

**Comment by MysterAitch** [comment]
I'll have a closer look later today but no objections here :)

**Pull request merged**
