### PR TITLE
Add two methods in class VisitorMap for debug purposes

### PR DESCRIPTION
**Pull request by Laughh**
The method `keySet()` and `entrySet()` are still based on hash code and the built-in `equal()` method, and there is no way to get all keys and entries, so I added two address-sensetive methods to get them  which are more convenient for debugging.

### CODE REVIEW

**Comment by jlerbsc** [comment]
Thank you for this suggestion, but I'm not sure that it's essential as the VisitorMap class accepts as parameters an implementation of a visitor for calculating the hashcode and another for implementing equals.

**Comment by Laughh** [comment]
> Thank you for this suggestion, but I'm not sure that it's essential as the VisitorMap class accepts as parameters an implementation of a visitor for calculating the hashcode and another for implementing equals.

As mentioned above, the two methods are used for debugging purpose. And the reason I wrote about them was precisely because I was having trouble debugging VisitorMap. And maybe there are two keys in VisitorMap, but when we print it, only one key showed.

**Comment by Laughh** [comment]
Is it useful for debugging purpose？

**Comment by jlerbsc** [comment]
No, I don't think so.

**Comment by Laughh** [comment]
Without the functions，is there any way to obtain all keys by using `keySet()` if two of them have same hash code and equals？Like what I describe in issue #4390

**Comment by jlerbsc** [comment]
There is no way of obtaining this result with the VisitorMap class, as it relies internally on the operation of the HashCodeVisitor class. But you can certainly either use the VisitorSet class or implement your own Visitor class to suit your specific needs or extend the CompilationUnit class and redefine the hashcode and equals methods.

**Comment by johannescoetzee** [comment]
Please see https://github.com/javaparser/javaparser/issues/4408 for a guide on how to resolve the git conflicts with the recent reformatting.

**Pull request closed without merging**
