### PR TITLE
Fix null pointer exception in error handling

### LINKED ISSUE #906: Error on InitializeConstructorParametersStatementsGenerator while mvn install
In InitializeConstructorParametersStatementsGenerator#findFieldInClass

I get :
```
[INFO] --- exec-maven-plugin:1.6.0:java (generate-javaparser-metamodel) @ javaparser-metamodel-generator ---
New source root at "K:\workspace\Javaparser\javaparser-core\src\main\java"
Parsing K:\workspace\Javaparser\javaparser-core\src\main\java\com\github\javaparser\metamodel\JavaParserMetaModel.java
Adding new file com.github.javaparser.metamodel.NodeMetaModel.java
Adding new file com.github.javaparser.metamodel.BodyDeclarationMetaModel.java
[WARNING] 
java.lang.NullPointerException
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.findFieldInClass(InitializeConstructorParametersStatementsGenerator.java:44)
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.generate(InitializeConstructorParametersStatementsGenerator.java:24)
```

Since nodeClass can only be null at this position.

### PR DESCRIPTION
**Pull request by matozoid**
Should fix #906

### CODE REVIEW

**Comment by DeepSnowNeeL** [comment]
The NPE is in the throw statement on nodeClass.getSimpleName()

**Comment by matozoid** [comment]
Yes, I was using it to traverse superclasses, and it ended up null when we reached `Object`. Now I'm using a copy called `searchClass` for the traversing so nodeClass remains as it is.

**Comment by DeepSnowNeeL** [comment]
Oh allright ! :)

**Comment by DeepSnowNeeL** [comment]
So the exception now throws correctly with : (while I mvn install)
```
java.lang.AssertionError: Couldn't find constructor parameter arg0 as a field, class BodyDeclaration
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.findFieldInClass(InitializeConstructorParametersStatementsGenerator.java:45)
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.generate(InitializeConstructorParametersStatementsGenerator.java:24)
```

**Comment by matozoid** [comment]
Ah, "arg0" indicates that core wasn't compiled with the "-parameters" argument, which you can find in the pom for core.

**Review by DeepSnowNeeL — APPROVED** [review]

**Pull request merged**
