### PR TITLE
fix the remove modifier implementation

### PR DESCRIPTION
**Pull request by signed**
The current one throws a ConcurrentModificationException if the modifier
that should be removed exists on the node

### CODE REVIEW

**Comment by signed** [comment]
Please trigger the travis-ci build again. To me it looks like a connection problem with maven central.

**Comment by ftomassetti** [comment]
travis-ci re-triggered

**Comment by matozoid** [comment]
Looks good to me!

**Comment by signed** [comment]
Looks like maven central download failed. Can you trigger the travis build please?

**Pull request merged**
