### PR TITLE
Fixes adding Block/Line comments leading to UnsupportedOperationEx

### PR DESCRIPTION
**Pull request by matf**
Fixes adding Block/Line comments leading to UnsupportedOperationException in LexicalPreservingPrinter

### CODE REVIEW

**Comment by ftomassetti** [comment]
Is this fixing a specific issue? Should we link that issue?

**Comment by matf** [comment]
No, I couldn't find a matching issue, and the contributing guidelines said to open a PR ;)

This fixes cases such as:

```java
String code = "public class Foo { }";
CompilationUnit cu = JavaParser.parse(code);
LexicalPreservingPrinter.setup(cu);

cu.getClassByName("Foo").get()
        .addMethod("mymethod")
        .setBlockComment("block");
LexicalPreservingPrinter.print(cu);
// --> java.lang.UnsupportedOperationException: BlockComment
//     at com.github.javaparser.printer.ConcreteSyntaxModel.forClass(ConcreteSyntaxModel.java:946)
//     at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.prettyPrintingTextNode(LexicalPreservingPrinter.java:412)
//     ..,
```

Not sure if this is the best way to fix it - I didn't quite understand why prettyPrintingTextNode() has a special case for JavadocComment only, and not for the other comments.

**Comment by ftomassetti** [comment]
Not complaining here :) Thank you for the PR, I was just wondering if we had to close an issue when merging this PR

**Comment by matozoid** [comment]
Thanks! It will be in next weekend's release.

**Pull request merged**
