### PR TITLE
[TESTCASE] Resolving MethodCallExpr with ResolvedUnionType as argument

### PR DESCRIPTION
**Pull request by daanschipper**
Providing test case for #1660.

### CODE REVIEW

**Comment by matozoid** [comment]
Is it supposed to pass?

**Comment by daanschipper** [comment]
Uhm no, the test fails locally...

**Comment by ftomassetti** [comment]
Here it says that checks have passed last time. Updating branch with changes from master

**Comment by ftomassetti** [comment]
It still passes on Travis

**Comment by matozoid** [comment]
Still passes. If this is still here next weekend I'll close it.

**Pull request closed without merging**
