### PR TITLE
Missing method addConstructor on EnumDeclaration #1128

### PR DESCRIPTION
**Pull request by DeepSnowNeeL**
Here is the fix :)

### CODE REVIEW

**Comment by matozoid** [comment]
Any idea why they disappeared in the first place? Maybe more stuff is broken.

**Comment by DeepSnowNeeL** [comment]
I can't find when we deleted it from EnumDeclaration so I suppose it was in TypeDeclaration before and since it has been moved to ClassOrInterfaceDeclaration we didn't copy it in EnumDeclaration at that time.

**Comment by matozoid** [comment]
I don't have access to an IDE right now - do we cover all TypeDeclaration subclasses with this PR?

Never mind, have access now

**Comment by matozoid** [comment]
Hmmm, it seems I moved them from `NodeWithMembers` to `ClassOrInterfaceDeclaration` around 3.2.2. I think we should stuff these in a `NodeWithConstructors` interface. Do you want to do that, or shall I pull and do the work afterwards?

**Comment by matozoid** [comment]
I'll give it a go then :-)

**Pull request merged**
