### PR TITLE
Fixing NullPointerException of getDeclarationAsString

### PR DESCRIPTION
**Pull request by chundongwang**
I was using getDeclarationAsString with my java library and hit this NullPointerException due to some methods not having parameters or throws. This change fixed the issue and my tool is happy now so hope it'd be helpful to others as well.

Thanks

### CODE REVIEW

**Comment by ftomassetti** [comment]
To me it seems fine, but I would prefer to fix it by initializing the lists (throws, parameters, etc) using empty lists instead of null. I think the original author did that for performance reasons but I am not sure it is worthy... and we had already a few of these errors.

**Comment by SmiddyPence** [comment]
I agree this part of larger problem, and related to #54.  The suggestion in #54 is ok, but it only caters when access lists as properties rather than fields.  In this case putting similar code around all field access is pretty grim.

Not sure what the lesser of two evils is here.

**Comment by chundongwang** [comment]
To me I would rather keep the existing behavior since probably not a lot functions would have both parameters and throw expressions. Rather than this, having two identical/similar code in two different places bites me more.

**Comment by ftomassetti** [comment]
Maybe we could do the lazy initialization thing in getParameters and getThrows and use them in foreach loop so we fix this problem with a smaller change AND we avoid returning null in getParameters and getThrows.

It is potentially true that users could expect getParameters and getThrows to return null, but imho this is bad and should be fixed eventually

**Comment by chundongwang** [comment]
I tried to make it lazy initialization and found that DumpVisitor is checking null of getParameters and getThrows. And it'll put a "throw" there even if the method has no throw expression and caused several test failures.

**Comment by chundongwang** [comment]
I fixed the DumpVisitor and looked up the whole source tree and that seems to be it. However I agree that it might break some existing projects out there. I personally would like to do the right thing here but it's up to you.

**Comment by ftomassetti** [comment]
Thank you for your work, to me it seems great! @SmiddyPence do you think this pull request could be merged?

**Comment by SmiddyPence** [comment]
Definitely looks cleaner to me, +1

**Comment by ftomassetti** [comment]
then I think you should accept it, I do not think I have writing access on this project

**Comment by matozoid** [comment]
Better give you access then.

**Comment by ftomassetti** [comment]
Thank you, I immediately used this new acquired power to merge the branch :D
Thank you @chundongwang for your patch!

**Comment by chundongwang** [comment]
My pleasure!

**Pull request merged**
