### PR TITLE
Resolving ObjectCreationExpr with ObjectCreationExpr scope

### LINKED ISSUE #1711: Resolving ObjectCreationExpr.ObjectCreationExpr throws StackOverflow
I'm analysing some code which in itself is very strange, but apparently it's valid Java. 
Consider the following class and its builder

```java
public class Foo {
  public class Bar {
    public Foo build() {
      return Foo.this;
    }
  }
```

When resolving the `MethodCallExpr` `new Foo().new Bar().build()`, a `StackOverflowError` is thrown: 
```java
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.<init>(AbstractJavaParserContext.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.<init>(ObjectCreationContext.java:49)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:88)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:296)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:113)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:56)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:67)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:296)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:113)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:56)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:67)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:296)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:113)
```

### PR DESCRIPTION
**Pull request by malteskoruppa**
This should fix #1711. :-) I've explained there.

Not sure if this is the cleanest way to do it, though. :-/ @ftomassetti ?

### CODE REVIEW

**Comment by ftomassetti** [comment]
The solution in itself seems correct. If I had to express a wish would be seeing a test also for the code originally reported in #1711 which to me seems different from the one you used (no instantiation, just use of qualified this).

**Comment by malteskoruppa** [comment]
I don't mind writing some additional test, but If I understand #1711 correctly, the problematic expression was `new Foo().new Bar().build()`, so there was indeed an instantiation (even two). I think that the code sample with the qualified `this` that you are refering to was just meant to clarify what `Foo` and `Bar` and `build()` are meant to be in the context of this problematic expression. The qualified `this` expression (returned by `build()`) in itself is irrelevant to this example, it is not even ever parsed when resolving the expression `new Foo().new Bar().build()`. In other words, `build()` could return anything it wants and we would still get the same problem when attempting to resolve `new Foo().new Bar().build()`.

@daanschipper You wrote that example, what's your take? :-)

**Comment by daanschipper** [comment]
That example was abstracted from some source code that I'm analysing. It does indeed seem like resolving an `ObjectCreationExpr` with as scope another `ObjectCreationExpr` was the problem. 
But on the other hand, adding another unit test doesn't seem to hurt?

**Comment by malteskoruppa** [comment]
Sure, as I said, I don't mind -- I'm just not sure *what* should be tested. ;-)

**Comment by ftomassetti** [comment]
Ok, if the original creator of the issue think this is already tested then my bad, let's get this merged if @matozoid agree

**Comment by matozoid** [comment]
Wheeeee

**Pull request merged**
