### PR TITLE
Add a workflow step to verify code generation and formatting

### PR DESCRIPTION
**Pull request by johannescoetzee**
Test PR

### CODE REVIEW

**Comment by jlerbsc** [comment]
I don't know why, but there are validation errors when using the mvn spotless:check command. The validation on the last PR was also in error (https://github.com/javaparser/javaparser/pull/4477/checks).

> [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default-cli) on project javaparser-core: The following files had format violations:
[ERROR]     src\main\java\com\github\javaparser\ast\validator\language_level_validations\Java19Validator.java
...
[ERROR] Violations also present in:
[ERROR]     src\main\java\com\github\javaparser\ast\validator\postprocessors\Java21PostProcessor.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\language_level_validations\Java18Validator.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\postprocessors\Java18PostProcessor.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\postprocessors\Java19PostProcessor.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\language_level_validations\Java20Validator.java
[ERROR]     src\main\java\com\github\javaparser\printer\lexicalpreservation\PeekingIterator.java
[ERROR]     src\main\java\com\github\javaparser\utils\ClassUtils.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\postprocessors\Java20PostProcessor.java
[ERROR]     src\main\java\com\github\javaparser\ast\validator\language_level_validations\Java21Validator.java

**Comment by johannescoetzee** [comment]
Hmm, I'm not getting the errors for the violations present in the PostProcessors and Validators, but the failure in the last PR was legitimate (see the logs starting at https://github.com/javaparser/javaparser/pull/4477/checks#step:4:6775).

I'll open a PR to fix that, but I think I will also disable the ratcheting feature. This means that all files will be reformatted with `./mvnw spotless:apply` instead of just ones that changed from master, but this would help avoid any inconsistencies in the future.

**Comment by johannescoetzee** [comment]
https://github.com/javaparser/javaparser/pull/4478 fixes the formatting issue and adds a note about formatting to `CONTRIBUTING.md`

**Comment by johannescoetzee** [comment]
I was wondering about the possibility of formatting the code when PR workflows are run, instead of just verifying that the formatting is correct, but so far I'm not very optimistic.

From https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/
> Automated code formatting of pull request branches
>
> Important caveat 1: Due to [token restrictions on public repository forks](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token) these workflows do not work for pull requests raised from forks. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction

This caveat suggests it's not practical, but the post is fairly old, so something could have changed in the meantime.

**Pull request closed without merging**
