### PR TITLE
Improved method resolution

### PR DESCRIPTION
**Pull request by jjbr**
It turns out that method resolution in Java is quite involved when it comes to overloaded methods. The `MethodResolutionLogic#isMoreSpecific` method was a bit too simplistic and has been improved with this pull request (see the tests added in this pull request for some examples). I don't want to guarantee a 100% compliance with the JLS (we'd have to look at larger parts of the symbol solver code to verify this) but it's better than before.

### CODE REVIEW

**Comment by matozoid** [comment]
Thanks! But the build fails - did you run the slow tests too?

**Comment by jjbr** [comment]
No, will have a look and fix the remaining failing test!

**Comment by matozoid** [comment]
If you haven't figured it out yet: `mvn test -P AlsoSlowTests`

**Comment by jjbr** [comment]
There was one logic flaw that resulted in occasional misidentifications whether a method is more specific when the argument type is an array type (to be passed to method with variadic parameter). Most of the test failures were due to the expected resolution not being 100% correct and with the improved resolution logic the symbol solver now occasionally resolved a method more accurately than before. I fixed the logic flaw and the tests - everything should be fine now. :slightly_smiling_face:

**Comment by matozoid** [comment]
Thanks a lot!

**Comment by malteskoruppa** [comment]
Good work! :-)

**Pull request merged**
