### PR TITLE
Implementing ReflectionEnumDeclaration.internalTypes 

### LINKED ISSUE #1722: Error on resolving Map field type
field type : java.util.Map<String, Long>

````
java.lang.UnsupportedOperationException: InternalTypes not available for com.github.javaparser.symbolsolver.reflectionmodel.ReflectionEnumDeclaration
	at com.github.javaparser.resolution.declarations.ResolvedTypeDeclaration.internalTypes(ResolvedTypeDeclaration.java:46)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver.tryToSolveType(ReflectionTypeSolver.java:98)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:62)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:180)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:72)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:475)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.lambda$convertToUsage$2(JavaParserFacade.java:482)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:482)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:452)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:219)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:294)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
````

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1722 by implementing ReflectionEnumDeclaration.internalTypes

### CODE REVIEW

**Comment by matozoid** [comment]
Shall we wait for @jGauravGupta to supply some test code, or merge this?

**Comment by ftomassetti** [comment]
I am perfectly fine for waiting a bit to give @jGauravGupta the possibility to give us test code. If this does not happen in a week or so I think we can merge it as it is pretty straightforward.

**Comment by matozoid** [comment]
@jGauravGupta seems busy. Let's merge this.

**Comment by jGauravGupta** [comment]
Apologies I missed the thread notification, In future, I will also make sure to add test to reproduce the issue.

**Pull request merged**
