### PR TITLE
Add pre-in-post-order visiting to TreeVisitor #751

### PR DESCRIPTION
**Pull request by ryan-beckett**
This is my first time ever issuing a pull request, and it appears that I've got some unrelated commits from @ftomassetti that shouldn't be. If this so, please let me know, and I'll try to fix it. Otherwise, please review and comment. Let me know what you think about deprecating visitDepthFirst().

### CODE REVIEW

**Comment by ryan-beckett** [comment]
@ftomassetti's implementation is a post-order traversal, so now we have two duplicated methods in my request. You can disregard my pull request completely or go with my mine and remove his code.

**Comment by matozoid** [comment]
Looks good to me! Don't worry about the commits.

@ftomassetti your verdict please :)

**Comment by ryan-beckett** [comment]
@matozoid: If @ftomassetti agrees to use my request, I guess you could undo his commit, and I can remove his addition from my code and resubmit the request. Or, you can just copy my code into your own commit and tidy it all up.

**Comment by ftomassetti** [comment]
Green light from me. We could merge its PR and then remove my method as a follow up

**Comment by matozoid** [comment]
Merged! Thank you @ryan-beckett  :)

**Comment by matozoid** [comment]
Congratulations on your first PR!

**Comment by ryan-beckett** [comment]
Thanks @matozoid. Expect many more!

**Comment by matozoid** [comment]
Oh, I just spotted an important thing: the unit tests you added don't actually test anything - there is no check!

edit: oops, I missed two correct tests. I was confused with a stringbuffer that was being built but was not used for anything else.

**Pull request merged**
