### PR TITLE
Made Node setters return this

### PR DESCRIPTION
**Pull request by ghost**
As described in #476, made Node setters return this

### CODE REVIEW

**Comment by ghost** [comment]
Sorry for the import changes, that's IntelliJ doing it automatically 😟

**Comment by matozoid** [comment]
Good work!

Did you join through Hacktoberfest?

**Comment by ghost** [comment]
Actually yes :p I thought I could help since it didn't seem that hard and java is kinda my thing so. IntelliJ was complaining about the code style though but I just ignored that and tried to use yours (tabs instead of spaces etc)

**Comment by matozoid** [comment]
Cool! So Hacktoberfest actually works :) If you want to do more, you can check the editor settings files and their instructions here: https://github.com/javaparser/javaparser/wiki/Coding-Guidelines

**Pull request merged**
