### PR TITLE
Workaround for error in composition of JavaToken for < and <<

### PR DESCRIPTION
**Pull request by ftomassetti**
Tests will be committed as part of #654 because they reuse classes introduced there.

This error was found because of bugs reported by @cal101

### CODE REVIEW

**Comment by matozoid** [comment]
Oh ugh, is this for the horrible unreadable exception code in the grammar?

**Comment by ftomassetti** [comment]
Yes, I think is for that case. My understanding is that when recognizing type parameters if we see a token like ">>>" or ">>" we pretend is a ">" and rewind the character stream. However the value passed to JavaToken is incorrect. So we check the token kind and adapt the text accordingly.

**Comment by ftomassetti** [comment]
rebased to avoid conflicts

**Comment by matozoid** [comment]
Sorry for more comments, but can you put a bit of explanation in the code? I just know someone will come across it in five years and that person will be utterly confused.

**Comment by ftomassetti** [comment]
No problem, I was very surprised when I saw this!

**Comment by ftomassetti** [comment]
Comment added, rebased

**Comment by matozoid** [comment]
That's a lovely comment!

**Pull request merged**
