### PR TITLE
remove unused imports

### PR DESCRIPTION
**Pull request by signed**
Just to get rid of some warnings while picking through the code.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Why not? Thank you for taking care of this @signed !

**Comment by matozoid** [comment]
Thanks! If you like random maintenance, check out this one: #1976 :-)

**Comment by signed** [comment]
Almost done :)
https://github.com/signed/convert-junit4-to-junit5/tree/extend

**Comment by matozoid** [comment]
:-O

**Pull request merged**
