### PR TITLE
Cleaning up JSS code

### PR DESCRIPTION
**Pull request by matozoid**
I found a big bunch of simple issues in the JSS code that I thought I'd fix.

### CODE REVIEW

**Comment by ftomassetti** [comment]
88 files changed? We need a semantic diff :)

**Comment by matozoid** [comment]
@ftomassetti I've put semantic diff in the feature doc :-)

**Comment by matozoid** [comment]
@ftomassetti is this okay?

**Comment by ftomassetti** [comment]
To me it seems ok but it is too large for a proper, detailed review :)

**Comment by matozoid** [comment]
Yeah, that's the advantage of doing large PR's ;-)

**Comment by matozoid** [comment]
I'm pretty sure I didn't change anything functional.

**Pull request merged**
