### PR TITLE
EnumDeclaration.entries -> constants

### LINKED ISSUE #1386: Rename EnumDeclaration.entries to EnumDeclaration.constants
It's the JLS terminology.

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #1386

### CODE REVIEW

**Comment by ftomassetti** [comment]
I am not sure about this because constants could also mean public static final fields in my opinion. However it is true that JLS calls them constants...

**Comment by DeepSnowNeeL** [comment]
Because it actually compiles to constants and the enum becomes a class :
https://stackoverflow.com/a/31040243/1281193 :)

**Comment by ftomassetti** [comment]
Yes, that is true but there are different levels of abstractions between what developers see and what ends up in bytecode

**Comment by matozoid** [comment]
Also not that we already have a `EnumConstantDeclaration`.

**Comment by matozoid** [comment]
I'll let this go because nobody ever complained about the naming here.

**Pull request closed without merging**
