### PR TITLE
Introduce NodeWithOptionalScope interface and migrate apt expressions

### PR DESCRIPTION
**Pull request by arturbosch**
Proposal for #696 

Do you have any ideas for default methods for the new interface?

I found out that MethodReferenceExpr had also a setScope method which did not return an Optional, so this PR will break the api. What do you think?

### CODE REVIEW

**Comment by matozoid** [comment]
Thanks!

MethodReference always has a scope, so it shouldn't implement this interface. We could have NodeWithScope, but that would be for one node only, so don't bother.

No ideas for default methods here. You?

**Comment by arturbosch** [comment]
Ok, no interface for MethodReference!

Maybe something like removeScope (will set scope to null)?
I don't really know. My use cases are to ask if the scope is a NameExpr or another method/field chain etc but they would be too specific. I use javaparser more to traverse the tree and not (yet) manipulate elements.

**Comment by matozoid** [comment]
Oh yes, remove would be fine, we would have less to do for #700 then :)

Well, "remove" and MethodReference, and that's it then :)

**Comment by matozoid** [comment]
Thanks @arturbosch !

**Pull request merged**
