### PR TITLE
Improving annotation support: Implement ResolvedAnnotationDeclaration#hasDirectlyAnnotation(String)

### PR DESCRIPTION
**Pull request by malteskoruppa**
Because what better thing to do on a Saturday evening? :-)

### CODE REVIEW

**Comment by malteskoruppa** [comment]
Solves issue #1839

**Comment by matozoid** [comment]
> Because what better thing to do on a Saturday evening? :-)

Work on https://github.com/laamella-gad/walrick/ of course :-)

**Comment by malteskoruppa** [comment]
Sounds interesting! :)

**Comment by matozoid** [comment]
@ftomassetti - can you spread your wisdom here too?
@malteskoruppa - can you give this a descriptive name? (Can be a copy of the issue name)

**Comment by ftomassetti** [comment]
Looks good to me!

**Review by ftomassetti — APPROVED** [review]
+1

**Comment by matozoid** [comment]
Thanks everyone :-)

**Pull request merged**
