### PR TITLE
Remove deprecated code leading up to 3.0

### PR DESCRIPTION
**Pull request by matozoid**
This felt so good :) :) :)

@DeepSnowNeeL - there is one deprecated method left. It is used by a unit test. Can you remove it the right way?

### CODE REVIEW

**Comment by DeepSnowNeeL** [comment]
Are you talking about `ASTHelper.addTypeDeclaration(cu, type);` in ClassCreator ?
If yes, 
change 

```
// create the type declaration 
ClassOrInterfaceDeclaration type = new ClassOrInterfaceDeclaration(EnumSet.of(Modifier.PUBLIC), false, "GeneratedClass");
ASTHelper.addTypeDeclaration(cu, type);
```

to

```
// create the type declaration 
 ClassOrInterfaceDeclaration type = cu.addClass("GeneratedClass");
```

**Comment by matozoid** [comment]
Thanks! Can I get a +1?

**Comment by ftomassetti** [comment]
+1

**Comment by DeepSnowNeeL** [comment]
+1 (to continue on this, #409 should be included in 3.0 too)

**Pull request merged**
