### PR TITLE
Update version of Javassist to 3.23.1-GA

### PR DESCRIPTION
**Pull request by stefanleh**
Update version of Javassist to 3.23.1-GA

### CODE REVIEW

**Comment by ftomassetti** [comment]
If tests pass I have nothing against this
+1

**Comment by stefanleh** [comment]
[ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:3.0.1: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:3.0.1 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-source-plugin/3.0.1/maven-source-plugin-3.0.1.pom , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by matozoid** [comment]
I restarted it to see if it is temporary.

**Comment by matozoid** [comment]
It was temporary. Thanks @stefanleh !

**Pull request merged**
