### PR TITLE
[TESTCASE] for lexical preservation and whitespace after modifiers.

### PR DESCRIPTION
**Pull request by matozoid**
See #1568

### CODE REVIEW

**Comment by ftomassetti** [comment]
The first test fails because a newline was expected after the annotation typically. Given it is not there the lexical preserving printer does not add it because it thinks it is a choice of the user do not have one. Of course the resulting code does not compile...

**Comment by ftomassetti** [comment]
The result from `extractReshuffledDiffElements` is not good I think...

**Comment by matozoid** [comment]
@ftomassetti - do you mean this is a pointless test case? What is not good about the result?

**Comment by ftomassetti** [comment]
Wasn't this integrated in #1994 ?
I think we should close it

**Comment by matozoid** [comment]
Okay!

**Pull request closed without merging**
