### PR TITLE
Make default JavaParserTypeSolver ParserConfiguration store tokens

### LINKED ISSUE #1580: Cannot get range of resolved method's declaration
This issue is related to the issue I opened previously, #1552.
Thanks to pull request #1557 now I am able to obtain the path of the Java class containing the resolved method declaration. I built the project from sources and it's working as expected.
Unfortunately a regression was introduced somewhere between release 3.6.5 and the current master branch that doesn't allow me to retrieve the range of the resolved method's declaration as I was doing before.
In particular, executing the exact same script that I listed in #1552, the output now is the following:
```
Analyzing method calls of file /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
L98C9,L98C33 -> it.matjaz.jnumerus.RomanInteger.setValueAndNumeral(int), (L122C5,L125C5)
Path: /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
L110C9,L110C35 -> it.matjaz.jnumerus.RomanInteger.setNumeralAndValue(it.matjaz.jnumerus.RomanNumeral), (L136C5,L139C5)
Path: /mcextractor/jNumerus/src/main/java/it/matjaz/jnumerus/RomanInteger.java
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at nl.tud.mcextractor.RunnerSimple.main(RunnerSimple.java:44)

Process finished with exit code 1
```
Line 44 is `wrappedDeclaration.getBegin().get().line`.
I am trying to understand where this regression was introduced and if I do so, I'll contribute with a pull request to fix it. Unfortunately my Java knowledge is quite limited.

### PR DESCRIPTION
**Pull request by joined**
Fixes #1580.
I would have liked to add a test but unfortunately there is no way I can get the tests to run, I get some obscure errors if I try to run them. Log here https://gist.github.com/joined/b97720fff0d531f005c347457940797c.
This is on a fresh VPS with Ubuntu 18.04.

edit: something is wrong with the log that I uploaded, will post soon the correct one
edit2: nevermind, it was just Github truncating the end of the log

### CODE REVIEW

**Comment by matozoid** [comment]
Well, you can remove `.setAttributeComments(false)` too, since that's removing information that used to be available too.

**Comment by matozoid** [comment]
And thanks, by the way :-)

**Comment by joined** [comment]
Done! Do you have any idea of the reason why my tests are failing?

**Comment by matozoid** [comment]
It's just AppVeyor. Lately that has been failing since the build takes too long. (I think AppVeyor is just overloaded though)

**Comment by matozoid** [comment]
And thanks :-)

**Comment by joined** [comment]
@matozoid I wasn't referring to the CI, I was referring to running the tests on my Ubuntu machine.
I discovered that the problem was that I was using the openjdk-11-jdk and probably the Maven Surefire plugin is not compatible with this version.
I wonder why they decided to make OpenJDK 11 the default version on Ubuntu 18.04, giving all the things it breaks.

**Comment by matozoid** [comment]
I was suddenly scared I missed a release, but sheesh, JDK 11 isn't anywhere near done?!

**Pull request merged**
