### PR TITLE
Improved JavaParserTypeVariableDeclaration tests

### PR DESCRIPTION
**Pull request by 4everTheOne**
This PR contributes with tests for JavaParserTypeVariableDeclaration to increase the line coverage.

The tests were design with the objective of being reusable by other Tests that depend on them to make them consistent. For example, if we now want to add unit tests for JavaParserFieldDeclarationTest we can simple implement ResolvedFieldDeclarationTest and be sure that the shared behavior between all ResolvedFieldDeclaration is consistent between them. 

**Note:**
Some tests are disabled due to additional work. 
As example in the test _declarationMostBeAssociatedToAst_ we would expect that all of the ResolvedDeclaration most implement AssociableToAST. This is not the case, so i left the test disabled.
https://github.com/javaparser/javaparser/blob/c6383311608bd392df8e9801c3ebbe322f7f4f9b/javaparser-core-testing/src/test/java/com/github/javaparser/resolution/declarations/ResolvedDeclarationTest.java#L96-L107

Do you think this can help the project?

### CODE REVIEW

**Comment by jlerbsc** [comment]
In my opinion dependency between javaparser-symbol-solver-core and javaparser-core-testing is not desirable because each test project has its own scope. Except that all tests that improve the code coverage is welcome.

**Comment by 4everTheOne** [comment]
Thanks for you opinion @jlerbsc! I can see your point and it makes sense.
This two commits fixes it.

**Comment by 4everTheOne** [comment]
Note that all the tests have passed but an error occurred while executing the upload of the data.

**Comment by jlerbsc** [comment]
The failing check seems to be related to codecov so there is no reason not to merge this PR. Thanks for this contribution.

**Pull request merged**
