### PR TITLE
Create a super type for Constructor- and MethodDeclaration - #738

### PR DESCRIPTION
**Pull request by arturbosch**
I hope its not to late @matozoid 

One thing that I don't like in this implementation is, that i've created setXXInternal(..) methods for all setter which return the declaration itself eg.:
```
    @Override
    public ConstructorDeclaration setModifiers(final EnumSet<Modifier> modifiers) {
        setModifiersInternal(modifiers);
        return this;
    }

    protected void setModifiersInternal(final EnumSet<Modifier> modifiers) {
        assertNotNull(modifiers);
        notifyPropertyChange(ObservableProperty.MODIFIERS, this.modifiers, modifiers);
        this.modifiers = modifiers;
    }
``` 
Another solution would be to write
```
    @Override
    public T setModifiers(final EnumSet<Modifier> modifiers) {
        ...
        return (T) this;
    }
```
with unchecked casts ... someone likes unchecked casts? What if one a user would extend CallableDeclaration and do not a subtype as T? I would like to hear your opinion?

Referenced issues #738

### CODE REVIEW

**Comment by matozoid** [comment]
We've been using two approaches until now: do the unchecked cast, or, well, take a look at `setAnnotations` in `Type` and `UnionType`

I prefer moving to the last one, because it would help us get rid of the `<?>` on some nodes (like TypeDeclaration)

**Comment by matozoid** [comment]
`setNameInternal`: try `setName`, and calling it with `super.setName` - that's one less naming convention to worry about.

**Comment by arturbosch** [comment]
That would work if i remove all the interfaces from CallableDeclaration and put them on the subtypes. That's also in Type and UnionType. Do you mean this way?

**Comment by matozoid** [comment]
Yes. I can see that it affects quite a lot of setters, but getting rid of useless `<?>` is a good thing. I'll open an issue to do this for other nodes too.

**Comment by matozoid** [comment]
Alternatively, implement `CallableDeclaration` as an interface like the NodeWith... interfaces.

**Comment by arturbosch** [comment]
I moved the interfaces to the subtypes and renamed the internal methods. I think having the attributes in one place is nicer than just an interface.

**Comment by matozoid** [comment]
+1 from me :)

**Comment by matozoid** [comment]
Sorry for breaking your branch :-|

**Comment by arturbosch** [comment]
I hope I fixed it though the GitHub GUI. First time! :D. Are we waiting for more feedback ?

**Comment by matozoid** [comment]
If there is no feedback for a few days, then that's all the feedback we're going to get :)

**Pull request merged**
