### PR TITLE
Update version reference on main page

### PR DESCRIPTION
**Pull request by sebkur**
Currently version 2.2.2 is referenced while 2.5.1 is really the latest

### CODE REVIEW

**Comment by matozoid** [comment]
Hmmm, I thought this was automatically generated. @ftomassetti - do you know how?

**Comment by ftomassetti** [comment]
What is the main page?

**Comment by sebkur** [comment]
http://javaparser.github.io/javaparser
which redirects to
http://javaparser.org

**Comment by sebkur** [comment]
I'm assuming this is hosted through GitHub pages

**Comment by matozoid** [comment]
I'll just merge this and open a new issue.

**Comment by matozoid** [comment]
Thanks for the PR, by the way :)

**Pull request merged**
