### PR TITLE
Fix bug in VisitorSet.toString()

### PR DESCRIPTION
**Pull request by Laughh**
Hello, I find a bug in VisitorSet.toString() due to missing a space, and the last useful character will be removed, causing a wrong output.
- The right output: 
image

- The wrong ouput:
image

### CODE REVIEW

**Comment by jlerbsc** [comment]
Can you add a unit test that demonstrates the problem and its resolution.

**Comment by Laughh** [comment]
Sure, I added a test for VisitorSet with `Type`, and the original output of the test is `[void,Strin]`, which is wrong due to the the Line 157 in `VisitorSet.toString()`,  the first arg `sb.length() - 2` will delete the last useful character, and now I have fixed it by setting the separator as `', '`.

**Comment by jlerbsc** [comment]
I don't think the correction is correct. It would have been better to replace the last comma with a square bracket. This is what the method tries to do when the set contains at least one object. You can propose a new PR that avoids adding elements to the standard output. You can also add tests for cases where there are no elements in the list, or a single element, or more than one element.

**Comment by Laughh** [comment]
> I don't think the correction is correct. It would have been better to replace the last comma with a square bracket. This is what the method tries to do when the set contains at least one object. You can propose a new PR that avoids adding elements to the standard output. You can also add tests for cases where there are no elements in the list, or a single element, or more than one element.

Okay, I will open a new PR to fix it, thank you.

**Pull request closed without merging**
