### PR TITLE
[discussion] Follow up of #2279 -- change packaging

### PR DESCRIPTION
**Pull request by MysterAitch**
Follow-up from #2279 

I'm not sure if there's ANY appetite for this at all or what the motivation for the original PR was, but I stumbled across the old commit #2279 and wanted to see what it would take to make such a change... can't be THAT hard, right??

In fairness it wasn't particularly painful -- the main "hiccup" is the test cases which depend on a copy of the source code using the current packages so I had to go back and "undo" those. fwiw that commit seems to be a decent resource to highlight where this is the case..? 

The other "issue" that came up is a few tests which have content in the resources file -- it took a small while to realise that the tests fail not because they're doing some odd reflection or something, but because the text files had jp imports and I had been somewhat overzealous in migrating those across. Details can be seen in the second commit.

Sidenote: Maybe there's a way to separate out tests which rely on a supplied copies of source code?

### CODE REVIEW

**Comment by matozoid** [comment]
Calling @edefazio :-)

**Comment by edefazio** [comment]
"can't be THAT hard, right??"
---Those were my famous last words before I wandered into the swamp

I would have wanted to "categorize" the failing tests (like 9 or so) that were just too hard for my silly little monkey brain to fix... 

I think most of the changes I made were REALLY easy and straight forward, I tried to document what I was doing, I think i got javaparser-core done in like an hour and a half.
 
...But (in the end of the day) the juice wasnt worth the squeeze,... meaning it's kinda pointless to adopt the changes unless you are going to change the package structure, so (for something like tests) it's kinda like "why bother"  ... and I hate saying this because I spent probably 30 hours or so trying to make sense of things... 
(Nothing I changed made the tests "better" or anything, but it was just grunt work to try to be the next step in allowing the package rename to occur)

(Keep in mind the entirety of the JSS vexes me, so, perhaps you'll have better luck)

**Comment by MysterAitch** [comment]
Link: #2249

**Comment by MysterAitch** [comment]
Closing this PR -- this is useful as a reference, but would pretty much need to be re-done from scratch to be mergable.

**Pull request closed without merging**
