### PR TITLE
renamed getChildrenNodes to getChildNodes

### PR DESCRIPTION
**Pull request by christiansafka**

### CODE REVIEW

**Comment by matozoid** [comment]
This broke the build. Please try again.

**Comment by christiansafka** [comment]
Fixing more

**Comment by matozoid** [comment]
If you use the "rename refactoring" of Eclipse or Intellij, it will do all the work for you.

**Comment by christiansafka** [comment]
I think it's okay now.

**Comment by matozoid** [comment]
Seems fine, thanks!

**Comment by matozoid** [comment]
It wasn't, so I'm fixing the problems now :-(

**Pull request merged**
