### PR TITLE
perform duplicate checking on all addImport methods

### PR DESCRIPTION
**Pull request by signed**
before this there was no duplicate checking for addImport(ImportDeclaration). This came as a surprise to me.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Well, I think that the API to build the AST should let you build an AST that is illegal for a variety of reasons. However we could have checks to later catch those errors.

**Comment by signed** [comment]
I agree building an invalid AST should be possible.
And there are still ways to do it.

```
cu.setImports(NodeList<ImportDeclaration>)
cu.setImport(index, ImportDeclaration)
cu.getImports().add(ImportDeclaration)
```

My point is about api consistency and the Principle of least astonishment.
Initially I used `cu.addImport(Class<?>)` and for duplication purposes later moved to `cu.addImport(ImportDeclaration)`. Given it is an overloaded method I expected the same contract. That not being the case surprised me.

**Comment by matozoid** [comment]
It's caused by the major Modifier overhaul from the last version, and I'm happy you're here to clean up the problems :-) It used to be a `Set`, so duplicates were impossible. I agree that the helper methods should help as much as possible, and the "basic" methods should be dumb.

However, conflicts :-(

**Comment by signed** [comment]
@matozoid resolved the conflicts

**Comment by matozoid** [comment]
@signed resolved more conflicts :-D

**Comment by signed** [comment]
@matozoid travis download failed again. But otherwise this should be ready to merge.

**Comment by matozoid** [comment]
Thanks again, @signed!

**Pull request merged**
