### PR TITLE
Issue76

### PR DESCRIPTION
**Pull request by ftomassetti**
Removing bubble sort and using Collections.sort (~mergesort)

### CODE REVIEW

**Comment by SmiddyPence** [comment]
In that case I would say go with `signum`.

**Comment by ftomassetti** [comment]
Renaming signOf as signum and using @SmiddyPence implementation. Merging.

**Comment by sebastiankirsch** [comment]
I know I'm late to the party, but you were so close, @ftomassetti: http://docs.oracle.com/javase/6/docs/api/java/lang/Integer.html#signum(int)
I will replace this quickly...

here we go: https://github.com/javaparser/javaparser/commit/4079fa3e9414232ed8a05ef04e045565ad850a67

**Comment by ftomassetti** [comment]
never late for improving things, thanks I learned a new one. Sorry for missing it in the first place

**Comment by sebastiankirsch** [comment]
No need to excuse ;)

**Comment by ptitjes** [comment]
@ftomassetti @SmiddyPence @sebastiankirsch Textual-search of 'sort' in the project reveals no other sorting methods, so I believe there are no other hidden manual sorts.

I add this to 2.1.

**Pull request merged**
