### PR TITLE
Dual license

### PR DESCRIPTION
**Pull request by ftomassetti**
Applying the changes suggested by @SmiddyPence in issue #144.

This is intended as a proposal, please revise the wording!

### CODE REVIEW

**Comment by ftomassetti** [comment]
Using this script we should be able to update the comment at the top of all source files, so if there is some rewording to do it will be easy. So please correct me!

https://gist.github.com/ftomassetti/400a2450e716e400184f

**Comment by ftomassetti** [comment]
@ptitjes suggested that the GPL license should be included too because the LGPL refers to it. I added it as LICENSE.GPL

**Comment by SmiddyPence** [comment]
I can't see the update to the grammar file. 

We also need a reference to the javalang or Walkmod project with respect to what @rpau requested.  I'm not sure what form this would take, perhaps @rpau can suggest?

**Comment by ftomassetti** [comment]
- corrected license as suggested by @matozoid 
- added reference to Walkmod

**Comment by ftomassetti** [comment]
I updated the comment in the grammar file, as suggested by @SmiddyPence

**Pull request merged**
