### PR TITLE
[TESTCASE]  New add statement test

### PR DESCRIPTION
**Pull request by moraispgsi**
Test for issue #2138

### CODE REVIEW

**Comment by moraispgsi** [comment]
@matozoid The problem seems to occur because there are two observers and because of that the difference is applied twice.

**Comment by matozoid** [comment]
Two observers? @ftomassetti - how can that happen?

**Comment by moraispgsi** [comment]
I need some help correcting this issue. Help @matozoid @ftomassetti

**Comment by ftomassetti** [comment]
I have no idea how two observers should end up being attached to the same node

**Comment by moraispgsi** [comment]
@ftomassetti I am not sure why this happens, I add an ifstmt to a blockstmt, I think this adds the first observer, after that I add a new statement to the ifstmt, and this I think adds a second observer. And when it comes to the second change the two observers are called in sequence, so two differences are computed and applied instead of one.

**Comment by matozoid** [comment]
Well, it should be easy to debug.

**Comment by matozoid** [comment]
It is caused by calling `LexicalPreservingPrinter.setup` three times on three different pieces of code. It creates three different observers that happily start propagating around when the pieces of code get put together.

@ftomassetti - what is the idea in this case? Should this be seen as bad user behaviour? Should the observers not propagate when one already exists? I guess this is more or less a useful use case...

**Comment by moraispgsi** [comment]
@ftomassetti

**Pull request closed without merging**
