### PR TITLE
Set com.github.javaparser.core as automatic module name

### PR DESCRIPTION
**Pull request by sormuras**
See #553

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Great idea!

**Comment by matozoid** [comment]
Anybody want to contribute this? I'm scared of installing the JDK 9 package and screwing up my linux again :-)

**Comment by matozoid** [comment]
Woops, wait a second: @sormuras - this sets the parent pom to have that module name, not the core module. How is this intended to work?

**Comment by sormuras** [comment]
I thought I edited the core module `pom.xml` -- I'll double check the jarred artifact(s) and will provide a second PR with a fix.

**Comment by sormuras** [comment]
Theses are the "installed" archives of this project:

- com.github.javaparser.javaparser:javaparser-testing:master-javaparser-parent-3.5.7-g94de8c7-6
- com.github.javaparser.javaparser:javaparser-core-generators:master-javaparser-parent-3.5.7-g94de8c7-6
- com.github.javaparser.javaparser:javaparser-metamodel-generator:master-javaparser-parent-3.5.7-g94de8c7-6
- com.github.javaparser.javaparser:javaparser-core:master-javaparser-parent-3.5.7-g94de8c7-6
- com.github.javaparser.javaparser:javaparser-parent:master-javaparser-parent-3.5.7-g94de8c7-6

Which should report as **`com.github.javaparser.core`**?

At the moment, the jar named `javaparser-core-master-javaparser-parent-3.5.7-g94de8c7-6.jar` does.

[1] Build log: https://jitpack.io/com/github/javaparser/javaparser/master-javaparser-parent-3.5.7-g94de8c7-6/build.log
[2] "Core Master Parent" artifact: https://jitpack.io/com/github/javaparser/javaparser/javaparser-core/master-javaparser-parent-3.5.7-g94de8c7-6/javaparser-core-master-javaparser-parent-3.5.7-g94de8c7-6.jar

**Comment by sormuras** [comment]
But because it is configured in the parent pom, all modules inherit the module name. Which is plain false. Will file a PR that moves the configuration in the core module pom.

**Pull request merged**
