### PR TITLE
Fix folder handle leak in java parser type solver

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by matozoid** [comment]
Of course we have `SourceRoot` for that, but this PR fixes the problem, so +1 from me.

**Comment by daanschipper** [comment]
Shouldn't you catch the possible IOException?

**Comment by Vampire** [comment]
> Of course we have SourceRoot for that, but this PR fixes the problem, so +1 from me.

You have `SourceRoot` for what? To work around that but?

> Shouldn't you catch the possible IOException?

Where?
In the test?
Why?

**Comment by daanschipper** [comment]
No after the try-with-resources, `Files.newDirectoryStream()` throws an `IOException`

**Comment by matozoid** [comment]
@Vampire we have SourceRoot to deal with directories of Java files.

**Comment by Vampire** [comment]
> No after the try-with-resources, Files.newDirectoryStream() throws an IOException

It was not caught before, why should I care to?

>@Vampire we have SourceRoot to deal with directories of Java files.

For the type solver?

**Comment by matozoid** [comment]
> For the type solver?

Uhuh. Why not? It's just a utility.

**Comment by daanschipper** [comment]
`JavaParserTypeSolver.parseDirectory()` is an internal method only used by the type solver. I'm using `SourceRoot` to read the .java files, but this method is still invoked.

Look at this stacktrace, I'm invoking `ClassOrInterfaceDeclaration.resolve()`:
```
parseDirectory:131, JavaParserTypeSolver (com.github.javaparser.symbolsolver.resolution.typesolvers)
tryToSolveTypeUncached:199, JavaParserTypeSolver (com.github.javaparser.symbolsolver.resolution.typesolvers)
lambda$tryToSolveType$4:157, JavaParserTypeSolver (com.github.javaparser.symbolsolver.resolution.typesolvers)
call:-1, 896134613 (com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver$$Lambda$308)
load:4793, LocalCache$LocalManualCache$1 (com.google.common.cache)
loadFuture:3542, LocalCache$LoadingValueReference (com.google.common.cache)
loadSync:2323, LocalCache$Segment (com.google.common.cache)
lockedGetOrLoad:2286, LocalCache$Segment (com.google.common.cache)
get:2201, LocalCache$Segment (com.google.common.cache)
get:3953, LocalCache (com.google.common.cache)
get:4790, LocalCache$LocalManualCache (com.google.common.cache)
tryToSolveType:156, JavaParserTypeSolver (com.github.javaparser.symbolsolver.resolution.typesolvers)
tryToSolveType:59, CombinedTypeSolver (com.github.javaparser.symbolsolver.resolution.typesolvers)
solveType:135, CompilationUnitContext (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
solveType:287, JavaParserClassDeclaration (com.github.javaparser.symbolsolver.javaparsermodel.declarations)
toReferenceType:378, JavaParserClassDeclaration (com.github.javaparser.symbolsolver.javaparsermodel.declarations)
getSuperClass:166, JavaParserClassDeclaration (com.github.javaparser.symbolsolver.javaparsermodel.declarations)
getAncestors:296, JavaParserClassDeclaration (com.github.javaparser.symbolsolver.javaparsermodel.declarations)
solveType:71, JavaParserTypeDeclarationAdapter (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
solveType:90, ClassOrInterfaceDeclarationContext (com.github.javaparser.symbolsolver.javaparsermodel.contexts)
convertToUsage:436, JavaParserFacade (com.github.javaparser.symbolsolver.javaparsermodel)
convertToUsage:413, JavaParserFacade (com.github.javaparser.symbolsolver.javaparsermodel)
toResolvedType:189, JavaSymbolSolver (com.github.javaparser.symbolsolver)
resolve:294, ClassOrInterfaceType (com.github.javaparser.ast.type)
visit:177, DataExtractor (visitors)
```

**Comment by Vampire** [comment]
That's exactly my point, I only see methods for doing the parsing with `SourceRoot`, but the `JavaParserTypeSolver` only accepts strings, files and paths as startpoint, so I don't see how the source root would help here. Can you enlighten us @matozoid?

**Comment by matozoid** [comment]
@Vampire you may be enlightening me here :-) The PR is fine as it is, by the way.

(I don't think I ever got to generalizing SourceRoot to make it easy to work with any kind of file)

**Pull request merged**
