### PR TITLE
[DRAFT] Attempt to fix raw NodeList type in visitors

### PR DESCRIPTION
**Pull request by matozoid**
@ryan-beckett @jimshowalter here's my attempt to get give NodeList a type parameter in the visitors. Currently fails in the `ModifierVisitor`. Any ideas?

See #1056

### CODE REVIEW

**Comment by ftomassetti** [comment]
What is the state of this one?

**Comment by matozoid** [comment]
No response from @ryan-beckett @jimshowalter - I'll delete it when nothing happened next Sunday, ok?

**Comment by ryan-beckett** [comment]
I'll take a look at it.

**Comment by ryan-beckett** [comment]
@ryan-beckett, @jimshowalter: The only way I can see to get rid of that warning is to change `NodeList.set(int, N)` to `NodeList.set(int, Node)`, which breaks type-safety. I can't think of an easy fix.

**Comment by matozoid** [comment]
@jimshowalter does not seem active anymore, nobody knows a way to fix, I'll close the original issue too. Thanks for looking, @ryan-beckett

**Pull request closed without merging**
