### PR TITLE
Various niceties

### PR DESCRIPTION
**Pull request by matozoid**
Cleaned up the code and added some things while inspecting issue #416

### CODE REVIEW

**Comment by matozoid** [comment]
Looks like I accidentally branched off from issue 417. If there are problems with that PR, this one should be changed too.

**Comment by DeepSnowNeeL** [comment]
You should note in the javadoc that getFields and getMethod are cloned
lists ? Maybe use Collection.unmodifiableList to enforce this ?

**Comment by matozoid** [comment]
Hmmm, good point. To be consistent with the rest of the code they should be modifiable, on the other hand all these modifiable lists are giving us a lot of trouble with people adding nodes without setting the parent correctly. I'll take a look.

**Comment by DeepSnowNeeL** [comment]
We could make the getMembers() return a unmodifiableList and add a generic
method addMember(BodyDeclaration<?> member) which will do the link job
correctly.(And do this for every other mutable list accessible today)

It would be breaking changes but goes on with the modifications for 3.0

**Comment by matozoid** [comment]
That's... ugly, but it would avoid the problem :-) I'll open an issue for it.

**Pull request merged**
