### PR TITLE
Add method reference resolution to the AST

### PR DESCRIPTION
**Pull request by matozoid**
Related to #2210.

Disclaimer: I don't know what I'm doing. I just copied stuff around until the test worked.

### CODE REVIEW

**Comment by matozoid** [comment]
@MassimilianoPoggi @scootafew @jlerbsc any comments on this?

**Comment by scootafew** [comment]
@matozoid this looks good to me! I'd be interested to test on different types of method reference (e.g. constructor calls) but can be raised as a separate issue later

**Comment by matozoid** [comment]
Yeah, at least there is a resolve method that does something now :-)

**Comment by jlerbsc** [comment]
Very good ... No need to look at Spoon now ;-)

**Pull request merged**
