### PR TITLE
Introducing TreeVisitor.visitLeavesFirst

### PR DESCRIPTION
**Pull request by ftomassetti**
Introducing the possibility of visiting a Tree starting by the leaves

### CODE REVIEW

**Comment by matozoid** [comment]
Does this have anything to do with https://github.com/javaparser/javaparser/issues/751 ?

**Comment by ftomassetti** [comment]
I wrote separately from #751 . We discuss it some time ago. Maybe #751 is about the same change

**Comment by matozoid** [comment]
Okay, can you talk to @ryan-beckett about this?

**Comment by ftomassetti** [comment]
Added comment in #751, waiting for an answer

**Comment by ryan-beckett** [comment]
@ftomassetti: Your addition doesn't affect me. I had intended on adding pre-order and post-order traversals. That's it for now.

**Comment by ftomassetti** [comment]
Perfect, than I rebase it and wait for @matozoid approval

**Comment by matozoid** [comment]
+1 :)

**Pull request merged**
