### PR TITLE
Fix issues with generics parsing and resolving with javassist

### PR DESCRIPTION
**Pull request by maartenc**
Fix some issues with generics and the javassist model:
- support <A,B<C>> return types
- support <A<? extends B & C>> bounds

Cfr. test cases...

Maarten

### CODE REVIEW

**Comment by ftomassetti** [comment]
Some tests are failing

**Comment by maartenc** [comment]
Looks like the AnalyseJavaSymbolSolver060Test is failing.
At first sight, it seems to perform better, because the test is expecting ERROR in some places while now it lists generic types.

Could you give me some hint how to interpret this AnalyseJavaSymbolSolver060Test test class so I can check that the new behaviour is correct?

Maarten

**Comment by ftomassetti** [comment]
That test is a sort of smoke test, we check that it produces exactly the same output. However if your code fixes some errors we should update the expected output. I can do that for you, if you wish. Basically you have to uncomment certain lines before running the test and it will update the file used for the comparison

**Comment by ftomassetti** [comment]
These lines:
```
        // If we need to update the file uncomment these lines
//        if (!dstFile.exists()) {
//            PrintWriter writer = new PrintWriter(dstFile.getAbsoluteFile(), "UTF-8");
//            writer.print(output);
//            writer.close();
//        }
```

**Comment by ftomassetti** [comment]
I sent you a PR in your fork with the fixes to the file https://github.com/maartenc/javaparser/pull/1

**Comment by ftomassetti** [comment]
@matozoid this PR reduces significantly the errors in resolution with the testcase JSS 0.6.0 from tens to 5 total errors, so it is pretty sweet & important

**Comment by matozoid** [comment]
I like it when throwing away stuff fixes things :-)

**Comment by matozoid** [comment]
@ftomassetti "Add more commits by pushing to the `[JavassistGenerics](/maartenc/javaparser/tree/JavassistGenerics)` branch on [maartenc/javaparser](/maartenc/javaparser)"

**Comment by ftomassetti** [comment]
Can I push to that branch? How?

**Comment by ftomassetti** [comment]
ok, maybe I managed

**Comment by matozoid** [comment]
It's cool that you can push to someone else's branch - and a little invasive :-)

**Comment by matozoid** [comment]
Thanks @maartenc!

**Comment by maartenc** [comment]
wow, thanks for fixing the junit tests and merging this PR! :-)

**Pull request merged**
