### PR TITLE
Some few fixes and enhancements

### PR DESCRIPTION
**Pull request by ptitjes**
I reintroduced ASTHelper class, fix the parent management (it was not propagating correctly and there was a lot of replicated code so I factored the parent setting code), and GenericProviderVisitor was not returning the return values correctly.

### CODE REVIEW

**Comment by ptitjes** [comment]
Thank you :)

**Comment by matozoid** [comment]
No, thank you :)

On Sun, Apr 1, 2012 at 1:46 AM, ptitjes
reply@reply.github.com
wrote:

**Comment by ptitjes** [comment]
If you wish, I have a variant of DumpVisitor that respects blank lines from the input. It follows Node.getBeginLine, and getEndLine to determine if there were some blank lines between non-modified nodes that were in the original tree.

I also have some type-checking (expected and actual type) stuff, although it is not implemented for all kind of expressions yet. It could be optimized by introducing a "feature" attribute in addition to parentNode to know in which property and index (for lists) of its parent node it is located. (I would only have to add that to the setAsParentNodeOf() method).

Tell me what you think about it.

**Comment by matozoid** [comment]
I've added you to the collaborator list. Add any features you like :-) I'll also add some issues to the issue tracker here.

**Comment by ptitjes** [comment]
Great :)

**Pull request merged**
