### PR TITLE
Fix resolving super methodcalls in anonymous inner classes (fixes #1962)

### LINKED ISSUE #1962: UnsolvedSymbolException thrown on super.<method> declaration inside inner class
Hi,

consider the following source:

```
public class X { 
    java.util.List x() { 
        return new java.util.ArrayList() { 
            public int size() { 
                return super.size(); 
            } 
        }; 
    } 
}
```

When trying to resolve the `MethodCallExpr`, I get an UnsolvedSymbolException:

```
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to super.size()', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:148)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
```

My code looks like this:

```
[...]
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver(false));
combinedTypeSolver.add(new JavaParserTypeSolver(new File("/path/to/my/sources")));

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

CompilationUnit cu = JavaParser.parse("public class X { java.util.List x() { return new java.util.ArrayList() { public int size() { return super.size(); } }; } }");
cu.accept(new MethodVisitor(), null);
[...]

public class MethodVisitor extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        ResolvedMethodDeclaration rmd = n.asMethodCallExpr().resolve();
        super.visit(n, arg);
    }
}
```

Is this a bug, or did I something wrong?

Maarten

### PR DESCRIPTION
**Pull request by maartenc**
Fixes #1962 .

### CODE REVIEW

**Comment by MysterAitch** [comment]
Seems to be good, with JLS 15.9 (specifically 15.9.5), though I do add the caveat that I don't fully understand it all :sweat_smile:

https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.9

I'm marking this as being for the next release, but will leave the PR open for a short while just in case there is any additional comment to add.

**Comment by MysterAitch** [comment]
Just added some documentation to the pr to help explain the difference between the two methods. 

Please do feel free to edit / revert these commits if you wish (I'll not be offended!), and instead I'll include them in a separate PR.

**Comment by maartenc** [comment]
looks good, thx! :-)

**Comment by MysterAitch** [comment]
In that case, let's kick-off the merge :)

**Pull request merged**
