### PR TITLE
Issue 1001: Fixing warning in the printer package

### PR DESCRIPTION
**Pull request by ftomassetti**

### CODE REVIEW

**Comment by matozoid** [comment]
See #1001

**Comment by matozoid** [comment]
Hmmm, what I do is select "analyze/inspect code" in Intellij, and run it on the printer package in this branch. This gives me 20 "possible bugs" of which two are "condition ... is always true", one is "equals() between inconvertible objects"  and one "collection may not contain element of type bla"

**Comment by ftomassetti** [comment]
Ok, now they are 4 (in the whole printer package), all of which are not bugs but things I have written in a certain way for clarity

screen shot 2017-07-19 at 17 35 11

**Comment by ftomassetti** [comment]
There are 14 of such warnings in other packages but I did not consider them

**Comment by matozoid** [comment]
That's cool, the plan is not to remove all warnings, only to check what they are about.

**Pull request merged**
