### PR TITLE
remove unnecessary double build for AppVeyor

### PR DESCRIPTION
**Pull request by matozoid**

### CODE REVIEW

**Review by ftomassetti — COMMENTED** [review]
It seems reasonable

**Comment by matozoid** [comment]
It doesn't seem to do much. I'm thinking one of the two phases can be removed completely.

**Comment by matozoid** [comment]
Well, looks like removing one phase hides the whole thing from the checklist here.

**Comment by matozoid** [comment]
Appveyor now does its whole run in 4 minutes :-) :-) :-) :-) :-)

**Pull request merged**
