### PR TITLE
Import organization

### PR DESCRIPTION
**Pull request by 4everTheOne**
In the previous PR #3781, the checkstyle tool was added do verify the quality of the code.
This PR is a continuation of that work, by organizing the imports according to the expected guideline.

With this PR new PRs will also be warned by pipeline if imports are not in the expected format.

### CODE REVIEW

**Comment by jlerbsc** [comment]
I do not wish to integrate this PR for the moment. In addition there are headers that have been removed. The expansion of all imports does not seem wise to me.

**Comment by 4everTheOne** [comment]
> In addition there are headers that have been removed. The expansion of all imports does not seem wise to me.

Thanks for the feedback. I applied the changes according with your suggestion.

> I do not wish to integrate this PR for the moment.

Feel free, when you think it's time for it :)

**Comment by jlerbsc** [comment]
Hi @4everTheOne can you create a new PR containing only the appropriate configuration and corresponding code update as it is difficult to understand what is the impact of the current PR on the code of the project. Thank you for this proposal and the time that you dedicate to this project.

**Comment by 4everTheOne** [comment]
The only configuration file that was changed is [dev-files/JavaParser-CheckStyle.xml](https://github.com/javaparser/javaparser/pull/3790/files#diff-eabee805a600afd0608f70f08e698ab1568d81ec6c7f0cf1e5e770715a01b2ce). 
The changes was done to remove the warning for avoiding the use of star imports, and to remove avoid error if the imports are not sorted alphabetically.

The other changes were executed by IntelliJ when i requested to "Organize Imports" using the project codestyle.
But if you prefer, i can separate the checkstyle configuration and the import organization into separate PRs

**Comment by jlerbsc** [comment]
> But if you prefer, i can separate the checkstyle configuration and the import organization into separate PRs

It would be a good idea.

**Comment by 4everTheOne** [comment]
Create PR https://github.com/javaparser/javaparser/pull/3799 with only the checkstyle changes.
This PR will be focused on the Import organization only.

**Comment by 4everTheOne** [comment]
In order to make the PR easier to review, i'll break it down in smaller PR.

**Pull request closed without merging**
