### PR TITLE
Add build information so java-symbol-solver can detect a JP version mismatch

### PR DESCRIPTION
**Pull request by matozoid**
See #959 

It generates this file:

```java
package com.github.javaparser;

/**
 * Some information that was available when this library was built by Maven.
 */
public class JavaParserBuild {
    public static final String PROJECT_VERSION = "3.2.8-SNAPSHOT";
    public static final String PROJECT_NAME = "javaparser-core";
    public static final String PROJECT_BUILD_FINAL_NAME = "javaparser-core-3.2.8-SNAPSHOT";
    public static final String MAVEN_VERSION = "3.3.9";
    public static final String MAVEN_BUILD_VERSION = "Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)";
    public static final String MAVEN_BUILD_TIMESTAMP = "2017-06-17T14:38:52Z";
    public static final String JAVA_VENDOR ="Oracle Corporation";
    public static final String JAVA_VENDOR_URL ="http://java.oracle.com/";
    public static final String JAVA_VERSION ="1.8.0_131";
    public static final String OS_ARCH ="amd64";
    public static final String OS_NAME ="Linux";
    public static final String OS_VERSION ="4.4.0-72-generic";
}
```

### CODE REVIEW

**Comment by matozoid** [comment]
So now you all know what OS I'm running :)

**Comment by DeepSnowNeeL** [comment]
Why not using the meta-inf/manifest.mf with implementation version,
buildtime and all that stuff ? It might be more "standard" ? :)

**Comment by matozoid** [comment]
@DeepSnowNeeL - yeah, I guess @ftomassetti could read `/META-INF/maven/com.github.javaparser/javaparser-core/pom.properties`. That would require no change in JP, but everyone who wants to do this would have to write the same bit of code. Let's see what he thinks.

**Comment by ftomassetti** [comment]
I think I would love to have a way to understand if the version of JP being used is the one I expect in JSS. I would think to do it using a static initializer like:

```
static {
    if (JavaParser.getVersion().equals("3.5.7")) {
        throw new RuntimeException("Hey, check your classpath! You seem to have the wrong JP version");
    }
}
```

Is there a way I could be able to easily read the value from manifest.mf at runtime?

**Comment by matozoid** [comment]
Well, the value is in that properties file I mention, so it would be "open that properties file from that exact path and read a specific key". Just take a look in the JP jar.

**Comment by matozoid** [comment]
Meh, I'll merge this. It's not like it's a major change or anything.

**Pull request merged**
