### PR TITLE
Fix indent of added comments

### PR DESCRIPTION
**Pull request by Implex1v**
After adding a comment to an existing node of an AST, the node after the comment loses it's indent when printing it with the `LexicalPreservingPrinter`.
Given this example
```java
public class Foo {
    void mymethod() {
    }
}
```
the resulting string would look like this:
```java
public class Foo {
    //line
void mymethod() {
}
}
```
I fixed the LPP so the result looks like this
```java
public class Foo {
    //line
    void mymethod() {
    }
}
```

I've added the indents to the LPPTest. Should I add another test or is it fine?

### CODE REVIEW

**Comment by matozoid** [comment]
Hey, that's awesome!

I'll bounce the test question back: do you think it's well tested this way?

**Comment by Implex1v** [comment]
It's never well tested :p
BBT: I'll add a test for a block comment and maybe another test.

**Comment by Implex1v** [comment]
It's never well tested ^^
BTT: I might add a test for the test file used for IntelliJ IDEA/Eclipse and check, if the indentions are as expected.

**Comment by matozoid** [comment]
Alright, Sunday I'll merge this in and we'll see if something has happened by then :-)

**Comment by Implex1v** [comment]
Yeah I found one problem with my new test and I'm going to fix it. I'll tell you, when I am done :)

**Comment by Implex1v** [comment]
I've fixed the metioned bug and added a new test. For me it looks fine and mergeable.

**Comment by matozoid** [comment]
Thanks!

**Pull request merged**
