### PR TITLE
Issue 1568 lexical preservation modifier whitespace

### LINKED ISSUE #1568: Wrong placement of spaces when adding modifiers to a method with annotations
The other issue.

Result of addingModifiersWithExistingAnnotations
```
class X {
  @Test
  public final   void testCase() {
  }
```
one space too many gets added

Result of addingModifiersWithExistingAnnotationsShort
```
@Overridepublic final  void A(){}
```
the space seems to get placed at the wrong position

```
    @Test
    public void addingModifiersWithExistingAnnotationsShort() {
        MethodDeclaration it = consider("@Override void A(){}");
        it.setModifiers(EnumSet.of(Modifier.PUBLIC, Modifier.FINAL));
        assertTransformedToString("@Override public final void A(){}", it);
    }

    @Test
    public void addingModifiersWithExistingAnnotations() {
        considerCode(
                "class X {" + EOL +
                        "  @Test" + EOL +
                        "  void testCase() {" + EOL +
                        "  }" + EOL +
                        "}" + EOL
        );

        cu.getType(0).getMethods().get(0).addModifier(Modifier.FINAL, Modifier.PUBLIC);

        String result = LexicalPreservingPrinter.print(cu.findCompilationUnit().get());
        assertEqualsNoEol("class X {\n" +
                "  @Test\n" +
                "  public final void testCase() {\n" +
                "  }\n" +
                "}\n", result);
    }
```

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1568 by revising several rules in the lexical preservation printer.

This stuff is so complex... but on the other hand we have hundreds of tests on this.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Thank you @matozoid for providing the test case

**Comment by ftomassetti** [comment]
Updated and merge conflict solved. @matozoid are you ok with merging this one?

**Comment by matozoid** [comment]
This stuff would be less complex if we extract the formatting ;-) But anyway, it's fine.

**Comment by ftomassetti** [comment]
Yes, extracting the formatting would be nice but I am not sure the logic can be not interwined with the diff logic. I am definitely sure the cose is very hard to understand as it is and some smarter approach would be very good. On the bright side we are building a set of test cases that will be very useful when we want to refactor this.

**Pull request merged**
