### PR TITLE
Fix: resolving constructors of anonymous inner classes implementing an interface fails

### PR DESCRIPTION
**Pull request by maartenc**
This might also fix issue #1757, although I didn't get the exception reported in that issue.

### CODE REVIEW

**Comment by matozoid** [comment]
We should check #1599 and #1436 too then, because they get referred too. But that doesn't block this PR.

**Comment by maartenc** [comment]
Hi @matozoid, I've added a testcase for issue #1436, and this PR also seems to fix that issue.

In the newly added testcase I also check the name of the resolved type, and there might be an issue about the name of the anonymous inner class, but I'm not sure what the spec says. I think the correct type should be B$1 (the first anonymous inner class of B), but JavaParser returns 'B.Anonymous-UUID' as type name. Anyway, if the name is incorrect, that is out of the scope of this PR imho.

Maarten

**Comment by maartenc** [comment]
About issue #1599 : I think that's about resolving methods of anoymous inner classes. This PR only addresses constructor resulotion, so I don't think it will solve that issue.

In issue #1599, the problem about resolving the constructor is mentioned in a comment, that should be fixed by this PR.

**Comment by matozoid** [comment]
> In the newly added testcase I also check the name of the resolved type, and there might be an issue about the name of the anonymous inner class, but I'm not sure what the spec says. I think the correct type should be B$1 (the first anonymous inner class of B), but JavaParser returns 'B.Anonymous-UUID' as type name. Anyway, if the name is incorrect, that is out of the scope of this PR imho.

Can you create a new issue for that?

If this is all done, then we can merge :-)

**Pull request merged**
