### PR TITLE
Create a Modifier node (attempt 2)

### LINKED ISSUE #912: FieldDeclaration or MethodDeclaration should not auto-reorder the nodes (or provide a way to get the original raw text if necessary)
I was trying to use this parser to validate that annotations are added in the correct order. The validation function is provided an instance of either FieldDeclaration or MethodDeclaration, and needs to determine if the annotations are in the correct order. The following, for example, would be valid:

@Nullable private int mVariable = 1;

But the following, would not:

private @Nullable int mVariable = 1;

However, the NodeList provided to FieldDeclaration (or MethodDeclaration) has already separated the annotations from the other modifiers, putting the annotations first, regardless of how they appeared in the raw Java code. Consequently, you can't identify the second example from an instance of FieldDeclaration.

One way to fix it would be to preserve the order in the NodeList that elements appear in the raw Java (or having a second NodeList to maintain this). A less good way, would be to expose the raw string.

### PR DESCRIPTION
**Pull request by matozoid**
`Modifier` is no longer an enum, it's a real `Node` now, so it's officially part of the AST. The enum is still there, it's called `Modifier.Keyword` now. `Modifier` has a field of that type.
Modifiers are no longer stored in an `EnumSet`, but in a `NodeList`.

Fixes #912 

This reverts commit 9a03bc62

### CODE REVIEW

**Comment by matozoid** [comment]
@ftomassetti can you help me with the lexical preservation part?

**Comment by matozoid** [comment]
I'll have to piggy-back this one on this PR: #851

**Comment by matozoid** [comment]
Back to the AccessSpecifier thing: I would agree that the access *level* or *scope* is a separate thing from the modifiers. We could have a seperate class for that.

**Comment by matozoid** [comment]
All the remaining stuff is "dunno" for me.

**Comment by ftomassetti** [comment]
> @ftomassetti can you help me with the lexical preservation part?

Ok, where I should look? There are 131 files changed and I got lost :D

**Comment by matozoid** [comment]
Check why the tests fail - there seem to be only one or two distinct types of failure :relaxed:

**Comment by ftomassetti** [comment]
PR on your PR sent

**Comment by matozoid** [comment]
PR merged!

**Comment by ftomassetti** [comment]
This is a big one!

**Comment by matozoid** [comment]
Yep, part of the API breaking in minor releases promise/threat :-)

**Pull request merged**
