### PR TITLE
[TESTCASE] Resolving constructors with generics

### PR DESCRIPTION
**Pull request by jjbr**
Test for #1827

### CODE REVIEW

**Comment by matozoid** [comment]
Thanks!

**Comment by matozoid** [comment]
@jjbr - can we get you to resolve the conflicts here?

**Comment by jjbr** [comment]
Done. The tests are obviously still failing until #1827 is resolved.

**Comment by jlerbsc** [comment]
I have integrated your unit test with a fix. Thank you for this contribution.

**Pull request closed without merging**
