### PR TITLE
Issue1441 node with members - Implementing review comments

### PR DESCRIPTION
**Pull request by kotari4u**

### CODE REVIEW

**Comment by matozoid** [comment]
Am I correct that the PR title is wrong?

**Comment by matozoid** [comment]
If this is about Java 10: you can update a PR simply by pushing more commits to that branch. No need to open another PR.

**Comment by kotari4u** [comment]
Sure will take care from next time (or) let me know if I can do now. I have added oraclejdk10 to travis but it is failing, As per the below link oraclejdk10 is supported for linux. But adding it to travis.yml failing travis build

https://docs.travis-ci.com/user/languages/java/

**Comment by matozoid** [comment]
Yes, you can do that now, the other PR is still open 👍 

We'll need to figure out what the problem is with the build. The symbol resolver seems to resolve some things differently. Interesting!

**Comment by matozoid** [comment]
@kotari4u I forgot to say: the tests that are failing can be run by doing `mvn clean install -PAlsoSlowTests`

**Comment by matozoid** [comment]
@kotari4u - can you please clean up the duplicate PR's?

**Comment by kotari4u** [comment]
Closing this PR as it is duplicate of https://github.com/javaparser/javaparser/pull/1666

**Comment by matozoid** [comment]
Thanks!

**Pull request closed without merging**
