### PR TITLE
Fix for "When visit ArrayCreationExpression initializer is missed in some cases. #321".

### PR DESCRIPTION
**Pull request by svlassiev**
Visit array initializer even if array creation expression had dimensions.

### CODE REVIEW

**Comment by ftomassetti** [comment]
It would be very nice to have a test for this also

**Comment by svlassiev** [comment]
OK. I'll take a look and add tests.

**Comment by matozoid** [comment]
Wait, I merged this a little early :) Tests are still appreciated!

**Comment by svlassiev** [comment]
Tests are still pending.

**Pull request merged**
