### PR TITLE
Helper methods

### PR DESCRIPTION
**Pull request by DeepSnowNeeL**
Awful formatting problem I know.. :/

### CODE REVIEW

**Comment by DeepSnowNeeL** [comment]
I think we should create NodeWithTypeArguments, I saw a lot of expressions which could use some helper methods like addTypeArgumet(Class) or Type or String :)

**Comment by matozoid** [comment]
Maybe do that when you pick up #468 ?

**Comment by matozoid** [comment]
Do you want this pulled now? It would be convenient, because I would have to merge it into my array branch.

**Comment by DeepSnowNeeL** [comment]
If you think it's better now go on, i'll continue to PR when I find new utility methods :)

**Comment by matozoid** [comment]
Here we go :)

**Pull request merged**
