### PR TITLE
JUnit test AnalyseJavaParserTest#parseTheRest() hangs on Windows

### PR DESCRIPTION
**Pull request by maartenc**
When srcFile is a file with a reserved name on Windows (like 'aux.java' for instance), Files.exists(srcFile) will return true, but opening an InputStream to it will hang forever. To avoid hangs, we check that srcFile is a regular file before trying to parse it.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Interesting! Should we point out the issue somehow to users? Being throwing some kind of exception or adding a warning somewhere

**Comment by maartenc** [comment]
No I don't think this is the task of the parser.
In addition, the hang of this JUnit test for instance is because the file `javaparser-symbol-solver-testing/src/test/test_sourcecode/javaparser_src/proper_source/com/github/javaparser/ast/body/FieldDeclaration.java` contains a variable named `aux`. There isn't even an Aux.java file to warn the user about.

Maarten

**Comment by maartenc** [comment]
An alternative place for this additional check could be in the `JavaParserTypeSolver#tryToSolveTypeUncached()` method where an unknown type is converted to a java sourcefile.

**Comment by ftomassetti** [comment]
@matozoid for me it is +1

**Comment by matozoid** [comment]
Okay, thanks for the contribution @maartenc :-)

**Pull request merged**
