### PR TITLE
[REFACTOR] Refactored logic of MethodResolutionLogic.isApplicable

### PR DESCRIPTION
**Pull request by stefanleh**
Refactored MethodResolutionLogic.isApplicable into DefaultApplicabilityCheckStrategy and made it configurable.

Please consider this as an idea to discuss.

### CODE REVIEW

**Comment by ftomassetti** [comment]
First question: is it strictly necessary to change package to two classes? This would cause an API change and leads to file changes in 336 files

**Comment by stefanleh** [comment]
I had to put the `ApplicabilityCheckStrategy` interface in the core project for being able to inject the strategy into `ParserConfiguration`. For the `isApplicable` method parameters i needed to move some other interfaces to the core project as well. This is the main cause for the many changes. I wish it would work without, but without loosing type safety i dont see another way. Do you?

**Comment by ftomassetti** [comment]
Also, I saw your comment in #1783 but could you explain me in more detail what is the goal of this change?

**Comment by ftomassetti** [comment]
Another thing: I saw you changed files under `javasymbolsolver_0_6_0/src`: you should not do that. That is a copy of the source code of an old version of a library later merged in JP. We use it to test JP and it should never be modified.

**Comment by stefanleh** [comment]
>Also, I saw your comment in #1783 but could you explain me in more detail what is the goal of this change?

I want to write a more simple implementation of the Strategy so that it would fit my needs (be more generous about the applicability).
As i stated i dont think i can find the bug in the current implementation (i am sure the applicable method exists as the code compiles and i have the sources - but unfortunately cant share them).

**Comment by stefanleh** [comment]
>Another thing: I saw you changed files under javasymbolsolver_0_6_0/src: you should not do that. That is a copy of the source code of an old version of a library later merged in JP. We use it to test JP and it should never be modified.

I will revert those changes. Tnx.

**Comment by ftomassetti** [comment]
In my opinion there should be just one way to solve methods: the correct one. I understand your problem and I agree that fixing method resolution is hard (it is very hard for me who wrote most of that stuff, I cannot imagine for others!). However I do not think it would be useful for users to be able to inject their own method resolution logic.
@matozoid what do you think?

**Comment by matozoid** [comment]
Agree with @ftomassetti - an alternative approach here would be to write your own custom logic to resolve methods to work around the current issue (without changing the library code,) but fixing the issue should definitely be the real goal.

**Comment by stefanleh** [comment]
Ok then. I will invest some more hours trying to debug and then go with the approach mentioned by @matozoid. Btw, I also tried to write a testcase to show the issue but without any luck. Guess its cause i used simple versions of the parameter types involved.

**Pull request closed without merging**
