### PR TITLE
correct a bug introduced with optionals

### PR DESCRIPTION
**Pull request by DeepSnowNeeL**
(I would love an alpha10 maven central with this fixed :D thx)

### CODE REVIEW

**Comment by matozoid** [comment]
Is it a problem if that alpha waits until coming Sunday?

**Comment by DeepSnowNeeL** [comment]
np :D

**Comment by matozoid** [comment]
Okay, this one really needs documentation to indicate what the difference is between "none" and "empty list"!

**Comment by matozoid** [comment]
Thanks!

**Pull request merged**
