### PR TITLE
issue333: configuring Travis to run on JDK 6, 7 and 8

### PR DESCRIPTION
**Pull request by ftomassetti**
As said in the subject

### CODE REVIEW

**Comment by ftomassetti** [comment]
Apparently this fails because of this:

`<java.version>1.8</java.version>`

Should we change it to:

`<java.version>1.6</java.version>`?

**Comment by ftomassetti** [comment]
Ok, in the code under testing there were some Java 8 features (the diamond operator). It should now compile also on Java 6

**Comment by ftomassetti** [comment]
Please ignore the failure from AppVeyor: in this branch we did not have the configuration for AppVeyor so it fails

**Comment by matozoid** [comment]
A while ago I configured the code to be all Java 8, except the core, including very strict checks that the core is 1.6 compatible, so I vote against these changes :)

**Comment by ftomassetti** [comment]
Oh, I see, sorry for the confusion then!
Would it make sense to compile just the core with the JDK 6?
If not I will just drop this PR

**Comment by matozoid** [comment]
If you can configure it that way, go ahead!

**Comment by matozoid** [comment]
#371 will help with this.

**Comment by matozoid** [comment]
Alright, @ftomassetti , how do we continue here? Everything is Java 8 now.

**Comment by matozoid** [comment]
@ftomassetti , you're cluttering the PR area! :)

**Comment by ftomassetti** [comment]
That is an old habit of mine :)
I am back from holidays. I guess we can just close this one if we moved to Java 8

**Pull request closed without merging**
