### PR TITLE
[TESTCASE] lex pres: Difference algorithm breaking indentation with identical statements #2203

### LINKED ISSUE #2203: LexicalPreservingPrinter Difference Algorithm breaks indentation after adding identical statements.
When using the LexicalPreservingPrinter, adding a statement identical to the previous statement breaks the Difference Algorithm because it confuses it, it makes it believe that the first statement was the one that was added, as a consequence the indentation breaks.

**Will be submitting a PR for this with a test case.**

### PR DESCRIPTION
**Pull request by moraispgsi**
Fixes #2203.

### CODE REVIEW

**Comment by moraispgsi** [comment]
@matozoid Resolving this issue is not a priority for me. I think I will leave the test case as a reference for now.

**Comment by matozoid** [comment]
That's okay!

**Comment by 4everTheOne** [comment]
Hi all!

I think this PR can now be closed, since issue #2203 has been closed and all of the provided tests are passing.

I would like to also use this message, to wish all the members and contributors a wonderful festive season!

**Comment by jlerbsc** [comment]
You are right. Thank you for your attention

**Pull request closed without merging**
