### PR TITLE
Issue 1801 - update copyright notices

### PR DESCRIPTION
**Pull request by MysterAitch**
This PR updates / normalises the copyright notices in all java files. 

Given the two histories for the two sections of the project, this PR uses two copyright notices (one part originally written by Julio, one part originally written by Federico).

This PR also updates the end year in the notice to 2019 (many are 2016, or 2018, or similar).

- ***JavaParser Core*** copyright notices have been updated to: 
```
/*
 * Copyright (C) 2007-2010 Júlio Vilmar Gesser.
 * Copyright (C) 2011, 2013-2019 The JavaParser Team.
 *
 * This file is part of JavaParser.
 *
 * JavaParser can be used either under the terms of
 * a) the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * b) the terms of the Apache License
 *
 * You should have received a copy of both licenses in LICENCE.LGPL and
 * LICENCE.APACHE. Please refer to those files for details.
 *
 * JavaParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 */
```

- ***JavaParser Symbol Solver*** copyright notices have been updated to: 

```
/*
 * Copyright (C) 2015-2016 Federico Tomassetti
 * Copyright (C) 2017-2019 The JavaParser Team.
 *
 * This file is part of JavaParser.
 *
 * JavaParser can be used either under the terms of
 * a) the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * b) the terms of the Apache License
 *
 * You should have received a copy of both licenses in LICENCE.LGPL and
 * LICENCE.APACHE. Please refer to those files for details.
 *
 * JavaParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 */
```

See also: 

#655 
#1801 
#1833 
#1835

https://github.com/javaparser/javasymbolsolver/issues/316

### CODE REVIEW

**Comment by MysterAitch** [comment]
I also updated the wiki to update the years to 2019, but haven't added the differentiation between jp core vs jss

https://github.com/javaparser/javaparser/wiki/Coding-Guidelines

**Comment by matozoid** [comment]
Hm, why are you changing history here? :-) We decided to call the whole group of contributors to the fork on GitHub "the javaparser team", and before that it was the project of Julio (and that was based on the grammar in the javacc distribution, which was contributed by... Uhhhh... Someone)

**Comment by MysterAitch** [comment]
Could you nudge me in the right direction re: the "correct" version of history? :)

**Comment by jlerbsc** [comment]
@matozoid, I agree with you, it is more correct to keep all the history of the project (without this initial work javaparser probably would not exist)

**Comment by MysterAitch** [comment]
I'm genuinely confused here. 

Could I double check that you've both read the actual changes, as opposed to only the description at the top of this pr? 

The reason I ask is because the only thing I can see is that perhaps the first post is misleading and could be worded better to emphasise that the two quoted sections are the NEW copyright notices. _(just had a go at pointing out this in the top message, but could likely use some additional edits)_

i.e. This means retaining Julio and Federico as the original writers (2007-2010 and 2015 for JP and JSS respectively), and THEN from 2011/2017 copyright is with "The JavaParser Team".

If it is something else and I am completely missing the point, please do spell it out for me because I don't seem to be getting the hint?

**Comment by matozoid** [comment]
Okay, I better take another look when I'm at home on my laptop instead of on my phone :-D

**Comment by matozoid** [comment]
Alright, my comments were indeed cause by seeing only half a line of text on my display at once. It's great - did you use some kind of tool that we can use every year?

**Comment by MysterAitch** [comment]
Yup - I don't recall the precise name but there's a tool within IntelliJ IDEA which allows you to specify the notice text. It can be refined to use different texts for varying "scopes" (in this case group of modules). It can then perform that analysis/update on the whole project. 

I'll put together some notes about it later this evening.

Now that they are consistently worded, I presume that a generator (or similar) could be used to do the update on build -- perhaps naively this could be done using a relatively simple regex?

**Pull request merged**
