### PR TITLE
Fix issue 134: Tailing semicolon cause ParseException

### PR DESCRIPTION
**Pull request by ftomassetti**
See #134 for details.

The solution includes tests.

### CODE REVIEW

**Comment by ptitjes** [comment]
I would say that we need a node to represent the semi-colon, in the same way it is done for EmptyXXX nodes. Else the semi-colon is dropped on dump.

Also does your code handles semi-colons just before the first import statement (that is after package decl) ?

**Comment by ftomassetti** [comment]
I am not sure we want a new node for that. I understand having `EmptyStatement` makes sense but `EmptyImport` probably not so much. While an `EmptyStatement` has a role depending on its position in the code, an `EmptyImport` would be always redundant.

I think we are talking about a pretty rare case (we have parsed tons of code and never encountered this problem so far). I do not know if we want to introduce in the AST a phantom node representing this spurious semicolon. I could not find a reference to it in the Language Specifics document.  

I think my code handles semi-colons also before the first import statement but I am not sure if it is what we want (so I did not write a test for that case: I am testing for extra semi-colons between two imports or after the last one).

**Comment by ptitjes** [comment]
I was not speaking about EmptyStmt, but about EmptyTypeDecl and EmptyMemberDecl.

I did check this WE and indeed this is not specified in the JLS, whereas Empty(Type|Member)Decl are (explicitly stated as a legacy for coders coming from C and that should not be used for new code, btw).

However, despite that is not specified, the IDEs (and I guess the Java compiler) accepts (and emit a warning) dangling semi-colons both after package decl and import decl (as it is done in between and after type declarations). I think this is consistent and I can't find any rational reasons to introduce support for dangling semi-colons in between and after import declarations _and omitting after package decl_. Please, we need to stay consistent.

As of a representation of it in the AST, we are parsing Java code and not interpreting. If we accept a piece of code, that must have a representation in a way or another. If we do not, we will break hash, equality, and the (not explicitly stated) we-dump-what-we-parsed contracts.

**Comment by ftomassetti** [comment]
`Please, we need to stay consistent.`

sure, the code does that already, I can add an additional test for that specific case

`As of a representation of it in the AST, we are parsing Java code and not interpreting. If we accept a piece of code, that must have a representation in a way or another.`

Well, it is not necessarily true the _abstract_ of AST tells us that we should represent meaningful information. This is way spaces or comments are normally not represented and a dangling semi-colon that has no effect whatsoever and it is basically irrelevant does not have necessarily to be included in the AST. I think the we-dump-what-we-parsed thing should not pollute the AST which should contain only information relevant and meaningful. I am not sure this is the case of the dangling semicolon because I do not understand what is representing in this context.

**Comment by matozoid** [comment]
@ptitjes @ftomassetti - can you please continue the discussion or close this?

**Comment by ptitjes** [comment]
I think there should be an AST node for any input element that are not white-spaces or comments, but I don't mind anymore ;)

**Comment by ftomassetti** [comment]
I think this point is not so much technical, it is instead a matter of interpreting what should or should not go in the AST.

My point is that there are semicolons with no meaning, for example extra semicolons among the import declarations.

I do not think we can reach an agreement without extra opinions. I would suggest that we wait for comments from others and if we do not receive them we close this PR. The problem is that #134 needs a solution anyway.

@matozoid @SmiddyPence @sebastiankirsch and any other interested, any thought on this one?

**Comment by matozoid** [comment]
As a user I would be annoyed with too much and too little information in the AST, but the "too much" option is the only one that I, as a user, could fix. I can't add information that JavaParser has thrown away. I vote keeping as much info as possible.... but I'm not a user ;)

**Comment by ftomassetti** [comment]
Mmm, I am convinced from the explanation of @matozoid . Maybe we can add some sort of marker for nodes which are just syntactical so that users could skip them easily. I will update this PR.

**Comment by matozoid** [comment]
This is quite connected to #22, I guess.

**Comment by ftomassetti** [comment]
I added nodes for the empty import declarations. Instead of creating a new class I just adapted `ImportDeclaration` to represent also empty import declarations. I considered two alternatives:
- having a specific class for EmptyImportDeclaration but in that case we would need a separate collection for holding empty import declarations in the `CompilationUnit`. At that point it would be hard to have an ordered list of normal and empty import declarations as they appear in the code.
- I considered creating an `AbstractImportDeclaration` from which to derive the `EmptyImportDeclaration` and the `NormalImportDeclaration`. However at that point the collection in `CompilationUnit` should have been a list of `AbstractImportDeclaration` and each time the user wanted to access an element it should have casted to a `NormalImportDeclaration` to use it. Sure, we could add some method like `asNormalImportDeclaration` on `AbstractImportDeclaration` but that would be not great

To me this seems the lesser evil but I am absolutely open to suggestions for alternative ways to represent the empty import.

**Comment by SmiddyPence** [comment]
Sorry got to this one late.  Personally I think ditching it as noise would be acceptable, but I understand the argument to keep it consistent with other empty elements.

+1 to ship in current incarnation.  I wouldn't want to see additional classes introduced to support such a narrow concept.

**Comment by matozoid** [comment]
People seem reasonably positive. Rebase & pull :)

**Comment by ftomassetti** [comment]
rebased, tests running

**Pull request merged**
