### PR TITLE
Enable slow tests on Travis

### PR DESCRIPTION
**Pull request by ftomassetti**

### CODE REVIEW

**Comment by matozoid** [comment]
That's all?!

**Comment by ftomassetti** [comment]
Yes :D

**Comment by ftomassetti** [comment]
Or no, that is not all. It is the wrong option, I will fix that

**Comment by ftomassetti** [comment]
It is probably `mvn test -P AlsoSlowTests`. Trying that...

**Comment by ftomassetti** [comment]
Ok, tried locally. The bad thing is that we have failing tests.

**Comment by matozoid** [comment]
Yeah, that's my pr then 😁

**Comment by matozoid** [comment]
Here comes my PR...

**Comment by matozoid** [comment]
Still failures, I'll go look.

**Comment by matozoid** [comment]
Still some broken tests. Analysing JSS and new JP give many more results - can this just be that JSS has gotten better?

**Comment by ftomassetti** [comment]
I like that line of thought :D

**Comment by matozoid** [comment]
Okay, the only problem left here is that AppVeyor builds have jumped from 20 minutes to more than an hour...

**Comment by ftomassetti** [comment]
Damn AppVeyor :)
I guess that 99% of cases Travis and AppVeyor should give the same answer and we can consider AppVeyor just as a double check

**Comment by matozoid** [comment]
Well, it wasn't AppVeyor that caused build times to explode, so I'll have to investigate :-(

**Comment by matozoid** [comment]
It's working! :-O

**Pull request merged**
