### PR TITLE
[TESTCASE] failing testcase for #1667

### PR DESCRIPTION
**Pull request by MarvinWyrich**
I have reproduced the problem in the smallest possible way and hope that the test is in the right place. As noted by @rnorth, the problem does not occur when not using `LexicalPreservingPrinter`.

### CODE REVIEW

**Comment by matozoid** [comment]
@MarvinWyrich - it seems to be passing - is your project on the latest version of JP?

**Comment by MarvinWyrich** [comment]
Yes, I forked the current master branch and worked on it. If you are referring to the Travis checks, it seems that not all tests from javaparser-core-testing are executed, probably due to [this issue](https://github.com/javaparser/javaparser/pull/1973). But I need you to help me out here, because I'm not an expert on this.

And this is how it looks like in Eclipse (at least for me):

failing unit test

**Comment by matozoid** [comment]
Ah right, I'll have to finish #1973 quickly then.

**Comment by ftomassetti** [comment]
Updating the branch to benefit from #1973

**Comment by ftomassetti** [comment]
Ok, this seems to be due to the fact that the type is not recognized as a child of the FieldDeclaration, because of the way fields are dealt with in FieldDeclaration. @matozoid this is biting us from time to time :)

So basically there is an issue because the NodeText sees "String" as a token, it does not understand it represent a child of the node. So when he expects to remove a child in the NodeText it cannot be found and the whole thing explode.

**Comment by ftomassetti** [comment]
PR based on this proposed in #1993 

Thank you for submitting the failing test case. When that PR is accepted this one should be closed

**Comment by matozoid** [comment]
@ftomassetti - I know, if you know of a real way to improve this, please open an issue.

**Comment by MarvinWyrich** [comment]
> PR based on this proposed in #1993
>
> Thank you for submitting the failing test case. When that PR is accepted this one should be closed

Thank you very much for your time and contributions to this project. Since the linked PR was accepted I close this one.

**Pull request closed without merging**
