### PR TITLE
Bugs due to null lists

### PR DESCRIPTION
**Pull request by ftomassetti**
In some situations we do not handle correctly empty lists. In visitors we just check for null lists but empty lists have the same meaning so they should be treated in the same way (derived from #54 )

### CODE REVIEW

**Comment by ptitjes** [comment]
Would you mind keeping tabs because it obfuscates your changes ? I propose that we make a reformat code just before 2.1, once we agreed on #120.

Also could git rebase -i and do some commit squashing ?

**Comment by ftomassetti** [comment]
Sure, I would just drop my last commit then, consider that the way the diff looks like depends on tab issues

**Comment by ftomassetti** [comment]
And it should be done. About the commit squashing I am not sure, I think it is better to have more granular commits.

**Comment by ptitjes** [comment]
Well in the second one you replaced tabs with spaces.
Also you can squash "Adding newline" and the first one.

**Comment by ptitjes** [comment]
@ftomassetti Well, I did not mean squashing everything in one commit. I also do think granular commits are better. But when you add a commit to fix another one, you can 'git rebase -i', move the fix commit, squash it, and then 'git -f push'

**Comment by ftomassetti** [comment]
You are right, I have squashed the commit about the newline

**Comment by ptitjes** [comment]
Nice! I may be picky :P but in the second one you still tabs to space... You may want to turn off you auto-format on save. IIRC you use Idea, then there is a 'View > Active Editor > Show Whitespaces' command.

**Comment by ptitjes** [comment]
I guess now you hate me for real :( Hopefully this will be easier when we will have all formated...

**Comment by ftomassetti** [comment]
Ok, I fixed the ones you suggested and I put back the tabs in the method _printModifiers_

**Comment by ptitjes** [comment]
That's good for me! +1

**Comment by ftomassetti** [comment]
Thanks :D

**Comment by ptitjes** [comment]
Thank you :P

**Comment by ftomassetti** [comment]
Thanks for merging

**Pull request merged**
