### PR TITLE
YAML and DOT printer classes and corresponding unit tests.

### PR DESCRIPTION
**Pull request by ryan-beckett**
[Here](https://codebeautify.org/yaml-validator/cb738ca7) is the YAML output, and [here](https://stamm-wilbrandt.de/GraphvizFiddle/?1505633397803#digraph%20%7B%0An8%20%5Blabel%3D%22root%20(CompilationUnit)%22%5D%3B%0An9%20%5Blabel%3D%22types%22%5D%3B%0An8%20-%3E%20n9%3B%0An10%20%5Blabel%3D%22type%20(ClassOrInterfaceDeclaration)%22%5D%3B%0An9%20-%3E%20n10%3B%0An11%20%5Blabel%3D%22isInterface%3D'false'%22%5D%3B%0An10%20-%3E%20n11%3B%0An12%20%5Blabel%3D%22name%20(SimpleName)%22%5D%3B%0An10%20-%3E%20n12%3B%0An13%20%5Blabel%3D%22identifier%3D'Foo'%22%5D%3B%0An12%20-%3E%20n13%3B%0An14%20%5Blabel%3D%22members%22%5D%3B%0An10%20-%3E%20n14%3B%0An15%20%5Blabel%3D%22member%20(MethodDeclaration)%22%5D%3B%0An14%20-%3E%20n15%3B%0An16%20%5Blabel%3D%22body%20(BlockStmt)%22%5D%3B%0An15%20-%3E%20n16%3B%0An17%20%5Blabel%3D%22statements%22%5D%3B%0An16%20-%3E%20n17%3B%0An18%20%5Blabel%3D%22statement%20(ExpressionStmt)%22%5D%3B%0An17%20-%3E%20n18%3B%0An19%20%5Blabel%3D%22expression%20(MethodCallExpr)%22%5D%3B%0An18%20-%3E%20n19%3B%0An20%20%5Blabel%3D%22name%20(SimpleName)%22%5D%3B%0An19%20-%3E%20n20%3B%0An21%20%5Blabel%3D%22identifier%3D'qux'%22%5D%3B%0An20%20-%3E%20n21%3B%0An22%20%5Blabel%3D%22arguments%22%5D%3B%0An19%20-%3E%20n22%3B%0An23%20%5Blabel%3D%22argument%20(StringLiteralExpr)%22%5D%3B%0An22%20-%3E%20n23%3B%0An24%20%5Blabel%3D%22value%3D'C%3A%20Docs'%22%5D%3B%0An23%20-%3E%20n24%3B%0An25%20%5Blabel%3D%22type%20(VoidType)%22%5D%3B%0An15%20-%3E%20n25%3B%0An26%20%5Blabel%3D%22name%20(SimpleName)%22%5D%3B%0An15%20-%3E%20n26%3B%0An27%20%5Blabel%3D%22identifier%3D'bar'%22%5D%3B%0An26%20-%3E%20n27%3B%0A%7D) is the DOT visualization for the following parsed code:

`
class Foo { public void bar(){ qux("C: Docs"); } }
`

Thoughts:

1. I kept the option to output the node type, and as you can see (in the output) the type is in parenthesis next to the node name. I think that's the best way to do it.
2. The indentation spaces is a fixed value for the YAML output.

Let me know if you have any issues.

### CODE REVIEW

**Comment by matozoid** [comment]
Busy day today, I'll take a look when I can!

**Comment by matozoid** [comment]
Ha, really cool to see a diagram like that :-D @SmiddyPence @ftomassetti click on the DOT link above!

Thanks for the work :-)

**Comment by ftomassetti** [comment]
Very nice indeed!

**Comment by ryan-beckett** [comment]
Absolutely, combining tools can be a powerful thing!

**Pull request merged**
