### PR TITLE
#1072_visitor_set

### LINKED ISSUE #1072: Create VisitorList and VisitorSet like VisitorMap
... for completeness.

### PR DESCRIPTION
**Pull request by ryan-beckett**
Fixes #1072

### CODE REVIEW

**Comment by matozoid** [comment]
Nice work! I noticed I made a mistake in the issue name, so there's now also a VisitorList to do :-)

**Comment by ryan-beckett** [comment]
@matozoid: All done.

**Comment by matozoid** [comment]
Thank you

**Comment by matozoid** [comment]
@ryan-beckett - if you tell me what your Twitter account is, I can @ you in the release tweets.

**Comment by ryan-beckett** [comment]
@matozoid: It's @blackcompe.

**Pull request merged**
