### PR TITLE
issue1230: adding method ResolvedTypeDeclaration.isAnonymousClass

### LINKED ISSUE #1230: Add method "isAnonymousClass" in ResolvedTypeDeclaration

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1230

### CODE REVIEW

**Comment by ftomassetti** [comment]
Merging master on it

**Comment by ftomassetti** [comment]
Merging master again on it :)

**Comment by ftomassetti** [comment]
It is a very minor change, so I will just merge it as tests passes, so it does not keep getting outdated and it can go in the next release :)

**Comment by matozoid** [comment]
I'll release in an hour or two, three :-)

**Pull request merged**
