### PR TITLE
[TESTCASE] Issue 412 missing comments

### LINKED ISSUE #412: Following comments are not always stored (missing/overwrite previous)
The following code outputs wrong results:

```
/* 1
1 *//*
2
2
 */
package
/* a *//* b */
//c
//d
com
/*alma*//*körte*/
//lófasz
//jóska
        .
pany
.
experiment
//z
//x
/*y*//*w*/
;
/*aa*//*bb*///cc
//dd
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseException;
import com.github.javaparser.ast.CompilationUnit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.function.Supplier;

public class Main {
    private static final String FILENAME = "C:\\Users\\alma\\"
            + "Documents\\NetBeansProjects\\1\\Experiment\\src\\main\\java\\com\\pany\\experiment\\Main.java";

    public static void main(String[] args) throws FileNotFoundException, IOException, ParseException {
//        try (FileInputStream fisTargetFile = new FileInputStream(new File(FILENAME))) {
//            final String content = IOUtils.toString(fisTargetFile, "UTF-8");
//            System.out.println(content);
//        }

        FileInputStream in = new FileInputStream(FILENAME);
        CompilationUnit cu;
        try {
            cu = JavaParser.parse(in, "UTF-8");
        } finally {
            in.close();
        }
        System.out.println(cu.toString());
        Main.<String[]>a(null, 1);
    }

    private static final <T> Supplier<T> a(T t, int a) {
        return () -> t;
    }
}
```

Actual output:

```
/* 1
1 */
package //d
com.pany/*alma*/
//*körte*/
//lófasz
//jóska
.experiment;

//z
//x
/*y*/
//*w*/
//dd
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseException;
import com.github.javaparser.ast.CompilationUnit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.function.Supplier;

public class Main {

    private static final String FILENAME = "C:\\Users\\alma\\" + "Documents\\NetBeansProjects\\1\\Experiment\\src\\main\\java\\com\\pany\\experiment\\Main.java";

    public static void main(String[] args) throws FileNotFoundException, IOException, ParseException {
        //        try (FileInputStream fisTargetFile = new FileInputStream(new File(FILENAME))) {
        //            final String content = IOUtils.toString(fisTargetFile, "UTF-8");
        //            System.out.println(content);
        //        }
        FileInputStream in = new FileInputStream(FILENAME);
        CompilationUnit cu;
        try {
            cu = JavaParser.parse(in, "UTF-8");
        } finally {
            in.close();
        }
        System.out.println(cu.toString());
        Main.<String[]>a(null, 1);
    }

    private static final <T> Supplier<T> a(T t, int a) {
        return () -> t;
    }
}
```

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #412.

### CODE REVIEW

**Comment by MysterAitch** [comment]
This test now produces all comments, but on separate lines. Does this mean that the underlying issue in #412 is fixed therefore this, and #412, can be closed? 

And which test case is the "desired" output layout/format? Does the expected output text file need to be updated?

**Buggy, per #412**
```java 
//z
//x
/*y*/
//*w*/
//dd
```

**Expected:**
```java
// z
// x
/*y*/
/*w*/
/*aa*//*bb*///cc
// dd
```

**Actual**
```java
// z
// x
/*y*/
/*w*/
/*aa*/
/*bb*/
// cc
// dd
```

**Comment by matozoid** [comment]
Oh, cool, this got randomly fixed somewhere along the road :-)

The first goal is to get all comments printed, and that seems to have been reached. A second goal can be to put comments in a beautiful place, but that's for later.

**Comment by MysterAitch** [comment]
@matozoid Given the tweaked test case passes, presumably this can be merged in too? :)

**Comment by matozoid** [comment]
@MysterAitch great!

**Pull request merged**
