### PR TITLE
Issue 902 generate range constructors

### PR DESCRIPTION
**Pull request by matozoid**
See #902 and #770

This got a little out of hand because I found all kinds of blemishes and also improved the generators a bit.

Some grammar improvements sneaked in too.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Nice idea to use the `@Generated` annotation.
Yes, it went a bit out of hand :D

**Comment by matozoid** [comment]
Sorry! It's the best way to get a PR accepted though: change each and every file in the project ;)

**Comment by ftomassetti** [comment]
Eh eh, that is true, and I kind of remember that someone did much worse a few months ago... so I am definitely not complaining here :D

**Comment by matozoid** [comment]
And there it goes!

**Pull request merged**
