### PR TITLE
[DRAFT] JEP 359: Records (Preview)

### LINKED ISSUE #2446: JEP 359: Records (Preview)
Add preview for records: https://bugs.openjdk.java.net/browse/JDK-8222777

... or let's not. I have a feeling this will change a lot in Java 15 because the syntax deviates from normal classes so much.

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #2446.

### CODE REVIEW

**Comment by MysterAitch** [comment]
@matozoid do you fancy giving this another look? :)

**Comment by matozoid** [comment]
@MysterAitch - not right now, but it is rather easy to pick up for others. Half the grammar is there, the tests are there and failing on what is still missing.

**Comment by MysterAitch** [comment]
I've been dabbling with it the last week or so - I shall post my work in progress up later today.

**Comment by matozoid** [comment]
I can do a review if you like.

**Comment by MysterAitch** [comment]
Superceded by the work in progress at #3022 :)

**Comment by matozoid** [comment]
Good work!

**Pull request closed without merging**
