### PR TITLE
Preparing release 2.4.0

### PR DESCRIPTION
**Pull request by ftomassetti**
Several users asked for a new relase and looking at the commits a lot of stuff has been changed since the last release (2.3.0). Therefore we could prepare a new relase (as discussed on gitter).

I tried to summarize the changes in the changelog. Anything else to do before going to fight with Nexus?

### CODE REVIEW

**Comment by ftomassetti** [comment]
Or maybe we use bintray and avoid all the pain :)

**Comment by matozoid** [comment]
I tried so hard to let github be the changelog :-(

**Comment by matozoid** [comment]
Here's step one: https://bintray.com/javaparser/JavaParser/javaparser/2.4.0

**Comment by matozoid** [comment]
Okay, 2.4.0 is now on Maven Central! Have fun :-)

**Pull request merged**
