### PR TITLE
Code Refactor

### PR DESCRIPTION
**Pull request by meghzman**
**Move Method**
Removed Feature envy smell: moved the method getExpressionBody from lambdaExpr to Statement class and hence reduced the code smell.

**Rename Variable**
In class ManipulationSteps, the argument variable in MethodDeclaration ‘ n’ is named to method methoddeclaration.

Push Down:
In class Type, method toDescriptor() is pushed to all child classes

Extract Method:
In class Difference, there was a complex method applyRemovedDiffElement, I have created another method out of it and removed complex method smell.

Extract Class:
In class StringEscapeUtils, there are many constants, so created a new class and moved all of them to that class

### CODE REVIEW

**Comment by jlerbsc** [comment]
Hi @meghzman thank you for your proposal but before pushing a PR can you check what you are pushing and at least follow the configuration recommendations of the JP project for your IDE. I also don't agree with integrating a PR that tries to treat several problems at the same time. You also do not specify what each of your modifications brings, which would allow us to better understand what you are proposing and what are the issues that led you to propose these changes.

**Comment by meghzman** [comment]
Hello Jean,
Thanks for your prompt response, so according to you, shohld I raise
individual PR for all of my changes separately?

**Comment by jlerbsc** [comment]
Configure your IDE (https://github.com/javaparser/javaparser/wiki/Eclipse-Project-Setup-Guide) and push individual PRs so reviewers can review them separately.

**Comment by meghzman** [comment]
Hello, I have pushed individual commits for better understanding and raised a new PR, please have a look. There are no errors and problems with my changed code, I will be very happy if you can approve this.

Thanks
Meghdoot

**Comment by meghzman** [comment]
Hello Jean, could you please check the changes and approve my PR?

regards,
Meghdoot

**Comment by MysterAitch** [comment]
Hi @meghzman , I am closing this PR, following my comment on #3535 -- hope it makes sense, but if not do feel free to follow up :+1:

**Pull request closed without merging**
