### PR TITLE
Get parameter names for methods and constructor obtained through reflection

### PR DESCRIPTION
**Pull request by ftomassetti**
Get the name of params obtained through reflection

### CODE REVIEW

**Comment by ftomassetti** [comment]
This should fix #1624

**Comment by matozoid** [comment]
@ftomassetti please give your PR's a better name :-)

**Comment by matozoid** [comment]
@ftomassetti - the build is breaking on this PR.

**Comment by ftomassetti** [comment]
Now it is passing

**Comment by matozoid** [comment]
Thanks!

**Comment by ftomassetti** [comment]
Sorry for not assigning the milestone

**Comment by matozoid** [comment]
My merge, so I have to add it :-)

**Pull request merged**
