### PR TITLE
Add breadth first travel to the TreeVisitor #355

### PR DESCRIPTION
**Pull request by zero33542**
I add visitBreadthFirst method in TreeVisirtor.java and add junit test in BreadthFirst directory.

### CODE REVIEW

**Comment by matozoid** [comment]
Oh hey, you put your tests in the package with the source code on the wiki :-) Do you want this stuff on the wiki as a sample, or do you want to move the test?

**Comment by zero33542** [comment]
Hi, I'll move the test out of wiki_samples. After doing that, do I need to PR again? Or I don't need to?

**Comment by ftomassetti** [comment]
We may want to do a squash after merging this

**Comment by matozoid** [comment]
@zero33542 if you push to the branch of the PR, github automatically notices, so everything is fine.

**Comment by matozoid** [comment]
Hm, I don't think the unit test actually does a test, just a System.out.println. Can you put something together that asserts it does?

**Comment by matozoid** [comment]
I've rewritten the tests and committed them through another PR.

**Pull request closed without merging**
