### PR TITLE
Transforming JSS into a set of modules under the JavaParser project

### PR DESCRIPTION
**Pull request by ftomassetti**
Ok.

It was not that complicate to merge it.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Seems to be failing on JDK9

**Comment by matozoid** [comment]
@ftomassetti builds have been failing randomly, maybe just kicking it on the travis site will help.

**Comment by ftomassetti** [comment]
Done, let's see

**Comment by ftomassetti** [comment]
+3.2% to coverage :D

**Comment by ftomassetti** [comment]
Ok, some tests seem to fail because of differences in the JDK 9:
```

Failed tests:   parseModifier(com.github.javaparser.symbolsolver.resolution.AnalyseNewJavaParserTest): Line 1 of src/test/resources/javaparser_methodcalls_expected_output/com_github_javaparser_ast_Modifier.txt is different from what is expected expected:<...this) ==> java.util.[EnumSet.of(E])> but was:<...this) ==> java.util.[Set.of(E...])>
  parseCoreJavaparsermodel(com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test): Line 43 of src/test/resources/javasymbolsolver_0_6_0/expected_output/java-symbol-solver-core/com_github_javaparser_symbolsolver_javaparsermodel_TypeExtractor.txt is different from what is expected expected:<...ist.of(jssType) ==> [com.google.common.collect.ImmutableList.of(E])> but was:<...ist.of(jssType) ==> [java.util.List.of(E...])>
  parseCoreJavaparsermodelDeclarations(com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test): Line 41 of src/test/resources/javasymbolsolver_0_6_0/expected_output/java-symbol-solver-core/com_github_javaparser_symbolsolver_javaparsermodel_declarations_JavaParserClassDeclaration.txt is different from what is expected expected:<...laration(this)) ==> [com.google.common.collect.ImmutableList.of(E])> but was:<...laration(this)) ==> [java.util.List.of(E...])>
  parseModelTypesystem(com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test): Line 4 of src/test/resources/javasymbolsolver_0_6_0/expected_output/java-symbol-solver-model/com_github_javaparser_symbolsolver_model_typesystem_PrimitiveType.txt is different from what is expected expected:<...leList.of(BYTE) ==> [com.google.common.collect.ImmutableList.of(E])> but was:<...leList.of(BYTE) ==> [java.util.List.of(E...])>
  testGetDeclaredMethods(com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclarationTest): expected:<28> but was:<40>
  testGetDeclaredMethods(com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclarationTest): expected:<67> but was:<69>
```

**Comment by ftomassetti** [comment]
There are a few cases in which we need to expect different values when running with Java 9... I handled that and now tests are passing

**Comment by matozoid** [comment]
I'll go peek at your branch. I'm especially interested in the maven config :-)

**Comment by ftomassetti** [comment]
Basically I use a gradle task to generate the pom and then mixed that with the pom configuration I copied from the javaparser modules

**Comment by matozoid** [comment]
Too many files changed for a decent review on Github, so here:
- take a peek at the plugins you're copying. I'm pretty sure you don't need osgi versioning (or do you?), method parameter names in class files, a javacc-support source directory, template filtering, and you surely don't want to use the module name "javaparser core" :-O
- javaparser-testing has configuration to stop it from being released. You can use that for your testing module too
- when are you available this weekend? I might need to ask questions to fix release problems.

**Comment by ftomassetti** [comment]
I cleaned a little bit the plugins. Also the symbol solver testing module should now be skipped during deploy.

About availability, on saturday morning I will be travelling while I will have guests in the rest of the weekend, so I am not sure when I will be home.

Do we have a way to do a dry-run release to check if we have errors that I can start looking into?

**Comment by matozoid** [comment]
I'll just release a few intermediary releases then and give feedback.

Meanwhile, please check the .ignore, intellij tells me these files are ignored but checked in:

# in directory: /home/danny/workspace/javaparser
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javassist_symbols/excluded_jar/excluded_jar.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javassist_symbols/included_jar/included_jar.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javassist_symbols/main_jar/main_jar.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javaparser-core-2.1.0.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javaparser-core-3.0.0-alpha.2.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0/lib/javaslang-2.0.3.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0/lib/javassist-3.19.0-GA.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0/lib/javaparser-core-3.3.0.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/javasymbolsolver_0_6_0/lib/guava-21.0.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/issue257/issue257.jar"
git rm --cached --force "javaparser-symbol-solver-testing/src/test/resources/junit-4.8.1.jar"
git rm --cached --force "javaparser-testing/src/test/java/com/github/javaparser/javadoc/JavadocExtractorTest.java"
git rm --cached --force "javaparser-testing/src/test/java/com/github/javaparser/javadoc/JavadocTest.java"
git rm --cached --force "javaparser-testing/src/test/java/com/github/javaparser/javadoc/description/JavadocInlineTagTest.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/description/JavadocDescriptionElement.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/description/JavadocSnippet.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/description/JavadocInlineTag.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/description/JavadocDescription.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/Javadoc.java"
git rm --cached --force "javaparser-core/src/main/java/com/github/javaparser/javadoc/JavadocBlockTag.java"

**Comment by ftomassetti** [comment]
I do not know how to get the list locally but jars are ignored in most Java projects, however we need those to test the symbolsolver, so I updated the gitignore. Then we have Java files with the word Javadoc... it seems that .gitignore contained "javadoc". I removed that. Also, I merge the last commits from master in the branch

**Comment by matozoid** [comment]
I'm okay with merging this. You too, @ftomassetti ?

**Comment by ftomassetti** [comment]
Yes.
Exciting times :)

**Comment by matozoid** [comment]
I'll do a test release tonight!

**Comment by ftomassetti** [comment]
Great! As soon as I can I will update JSS readme

**Pull request merged**
