### PR TITLE
Fix issue 2535 Comments within method missing indentation

### LINKED ISSUE #2535: Comments within method missing indentation
It seems that some comments within methods (presumably orphaned comments) do not get indented. This is with the default parser config. 

Here are some examples: 

```java
    public Java8Validator() {
        super();
        replace(modifiersWithoutDefaultAndStaticInterfaceMethodsAndPrivateInterfaceMethods, modifiersWithoutPrivateInterfaceMethods);
        add(defaultMethodsInInterface);
        remove(noLambdas);

        // TODO validate more annotation locations http://openjdk.java.net/jeps/104
        // TODO validate repeating annotations http://openjdk.java.net/jeps/120
    }
```

```java
    public Java8Validator() {
        super();
        replace(modifiersWithoutDefaultAndStaticInterfaceMethodsAndPrivateInterfaceMethods, modifiersWithoutPrivateInterfaceMethods);
        add(defaultMethodsInInterface);
        remove(noLambdas);
    // TODO validate more annotation locations http://openjdk.java.net/jeps/104
    // TODO validate repeating annotations http://openjdk.java.net/jeps/120
    }
```

```java
    @Override
    public void propertyChange(Node observedNode, ObservableProperty property, Object oldValue, Object newValue) {
        // do nothing
    }
```

```java
    @Override
    public void propertyChange(Node observedNode, ObservableProperty property, Object oldValue, Object newValue) {
    // do nothing
    }
```

### PR DESCRIPTION
**Pull request by jlerbsc**
Fixes #2535 .

### CODE REVIEW

**Comment by jlerbsc** [comment]
@MysterAitch I don't understand why there are compilation errors.

"package classes.com.github.javaparser does not exist" ??

**Comment by MysterAitch** [comment]
Looks like it was just a few remaining test cases to amend to accommodate the fix :+1:

**Comment by jlerbsc** [comment]
Thanks for your help.

**Comment by MysterAitch** [comment]
Added the behaviour change label as this corrects / changes in how code is printed (as shown in the changed tests).

**Pull request merged**
