### PR TITLE
issue506: some nodes have line zero

### PR DESCRIPTION
**Pull request by ftomassetti**
I have added a test to prove #506 and a workaround to reduce the issue.

### CODE REVIEW

**Comment by ftomassetti** [comment]
This fix should be enough to make JavaSymbolParser happy. The idea is to derive the position of an ArrayType from the position of the element type. It should reduce the number of elements without position (from the ArrayType, VariableDeclarationExpr and ExprStatement inherited the unknown position, propagating the issue). Still the ArrayBracketPair could have unknown position

**Comment by matozoid** [comment]
Can you make issues for what it would take to implement this perfectly?

**Comment by ftomassetti** [comment]
@matozoid I have opened #508 as a follow up. Imho, it is less critical than this one.

**Comment by ftomassetti** [comment]
thanks!

**Pull request merged**
