### PR TITLE
Upgrade dependencies in poms to latest versions

### PR DESCRIPTION
**Pull request by matozoid**
See title.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Are we sure the dependencies used in core are compatible with Java 6? Is there an easy way to test it?

**Comment by matozoid** [comment]
Core has no dependencies :)

**Comment by ftomassetti** [comment]
Very good observation :)

**Comment by matozoid** [comment]
+1?

**Comment by ftomassetti** [comment]
Sure +1!

**Pull request merged**
