### PR TITLE
Fixed creating Position using beginOf() or endOf() creator methods

### PR DESCRIPTION
**Pull request by lgawin**
Line was wrongly initialized

### CODE REVIEW

**Comment by ftomassetti** [comment]
Seems fine to me, I will go on and merge it because it seems an obvious fix.
Thank you so much @lgawin for fixing this!

**Comment by matozoid** [comment]
Does this need a fix in 2.1 as well?

**Comment by ftomassetti** [comment]
Well, I think it would be useful to do so, do you want me to create a 2.1 branch and put this commit in that branch? There are another couple of small fixes in the pipeline/already committed that could all end up in a 2.1.1 release

**Comment by matozoid** [comment]
If it's little work, go ahead :) If it becomes a lot of work, we have to consider if it's worth it, or if we just focus on 3.0

**Comment by ftomassetti** [comment]
I created a 2.1 development branch, I will write on gitter also

**Pull request merged**
