### PR TITLE
issue822: make addModifier notify about the change

### LINKED ISSUE #822: Add modifier does not notify about the change
In NodeWithModifiers:

```
    default N addModifier(Modifier... modifiers) {
        getModifiers().addAll(Arrays.stream(modifiers)
                .collect(Collectors.toCollection(() -> EnumSet.noneOf(Modifier.class))));
        return (N) this;
    }
```

This does not cause a notification. We could refactor it to invoke setModifiers, which does. The problem is we cannot call notifyChange directly from here I think.

### PR DESCRIPTION
**Pull request by ftomassetti**
fix #822

### CODE REVIEW

**Comment by matozoid** [comment]
Is this because EnumSet is being a pain? Do you think we should change it to a NodeList in the future?

**Comment by ftomassetti** [comment]
Well, the issue is just that we have this method in NodeWithModifiers wich should call notifyPropertyChange. The problem is that you cannot do that from NodeWithModifiers because it is not extending Node (even if the name let us understand a NodeWithModifiers is a Node). So we have to translate the addModifier in a setModifiers, because that method is implemented in the concrete class and it can invoke the Node.notifyPropertyChange method.
The problem here it is not EnumSet, is the lack of multiple inheritance that force NodeWithModifiers to be an interface and not a class extending Node.

**Comment by ftomassetti** [comment]
(rebased)

**Comment by matozoid** [comment]
Well, +1 then.

**Pull request merged**
