### PR TITLE
[DRAFT] Removal of JUnit 4 dependency from pom

### PR DESCRIPTION
**Pull request by MysterAitch**
From what I can tell, other than one case (described below) there is no explicit requirement to include junit 4 in the pom.

Removing it does not cause any tests to fail locally. I suspect that the "correct" behaviour might to be to tighten up the tests to fail when the dependency isn't present, but I haven't looked into it properly to be sure.

This draft pr is to trigger the CI checks to verify if the tests pass here too, and to potentially start discussion about the desired behaviour.

**Notes**
- JUnit 4 appears to be used in `MethodsResolutionTest#testConsistentMethodResultion` (indirectly by using a reflection solver?) -- tests still do pass when dependency is removed, though I'm unsure how/why (perhaps something to do with local setup?)

- JUnit 4 is used as a jar file (`junit-4.8.1.jar`) in some tests (see `CompilationUnitContextResolutionTest` and `AnnotationsResolutionTest`), but in those cases since the jar is included as a `JarTypeSolver``, the maven pom dependency is not required

### CODE REVIEW

**Comment by MysterAitch** [comment]
I have since come across #1208 and #2002 noting that JBehave can't run on JUnit 5 (not yet quite gotten my head around it, but specifically it seems to be due to the `JUnitReportingRunner` not working with JUnit 5?)

Somewhat concerning is this not being flagged up in the maven compile/test cycle (or, at least, not that I could see!) and also not in the travis/appveyor CI checks. Maybe JUnit 4 is being pulled in as a transitive dependency thus it doesn't matter if it's explicitly included in the pom?

Also, did these tests get ignored/disabled somehow and I just haven't figured out how to run them? 

_At the moment I can't even get the bdd module to compile/run inside IntelliJ, but given that maven clean/test/package commands all seem to execute without error I can only presume that there's something else going on or I'm missing something! Certainly not ruling out user error! I'll continue to investigate though :)_

**Comment by MysterAitch** [comment]
From what I can tell, all the test cases are passing but Travis is failing on the report generation element. 

I need to take a step back so will leave it be for a while. One of the example errors is pasted below for convenience of anyone else who wants to take a look.

```
Generating reports view to '/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave' using formats '[console, html, stats, txt, json, xml]' and view properties '{reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, decorated=ftl/jbehave-report-decorated.ftl}'
Failed to generate reports view to '/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave' using formats '[console, html, stats, txt, json, xml]' and view properties '{reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, decorated=ftl/jbehave-report-decorated.ftl}'
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.754 s <<< FAILURE! - in com.github.javaparser.ParsingTest
[ERROR] run(com.github.javaparser.ParsingTest)  Time elapsed: 1.744 s  <<< ERROR!
org.jbehave.core.embedder.Embedder$ViewGenerationFailed: View generation failed to /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave for formats [console, html, stats, txt, json, xml] and resources {reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, decorated=ftl/jbehave-report-decorated.ftl}
Caused by: org.jbehave.core.reporters.TemplateableViewGenerator$ReportCreationFailed: Report creation failed from file {AfterStories=[/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/AfterStories.txt, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/AfterStories.stats, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/AfterStories.html, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/AfterStories.json, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/AfterStories.xml], BeforeStories=[/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/BeforeStories.xml, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/BeforeStories.json, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/BeforeStories.stats, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/BeforeStories.txt, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/BeforeStories.html], com.github.javaparser.manipulation_scenarios=[/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.manipulation_scenarios.stats, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.manipulation_scenarios.xml, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.manipulation_scenarios.json, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.manipulation_scenarios.html, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.manipulation_scenarios.txt], com.github.javaparser.parsing_scenarios=[/home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.parsing_scenarios.txt, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.parsing_scenarios.stats, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.parsing_scenarios.html, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.parsing_scenarios.json, /home/travis/build/javaparser/javaparser/javaparser-core-testing-bdd/target/jbehave/com.github.javaparser.parsing_scenarios.xml]}
Caused by: org.jbehave.core.reporters.TemplateableViewGenerator$ViewGenerationFailedForTemplate: ftl/jbehave-report-decorated.ftl
Caused by: org.jbehave.core.reporters.FreemarkerProcessor$FreemarkerProcessingFailed: 
Freemarker failed to process template ftl/jbehave-report-decorated.ftl using configuration freemarker.template.Configuration@347f8029 and data model {name=com.github.javaparser.parsing_scenarios, format=txt, body=
(com/github/javaparser/parsing_scenarios.story)
```

**Comment by matozoid** [comment]
I wanted to check if coverage had decreased, but it seems Travis doesn't like the changes much :-(

**Comment by MysterAitch** [comment]
This was mostly an experiment to see if there is any need for the dependency. There is still lots I don't quite understand with respect to which components "talk" to each other re: the CI stuff and which ones contribute toward various statistics/reports etc., and then again confusion with how it runs (and which bits get run) by maven or other external tools....

Overall, my takeaway is that the more I dug the more it seems like rocking the boat with minimal actual benefit!!

**Comment by matozoid** [comment]
I'm afraid I'm not much help either. The build is a bit odd because coverage information is pooled or so? @SmiddyPence may know more

**Pull request closed without merging**
