### PR TITLE
Commenting

### LINKED ISSUE #1395: Document why JavaParserClassDeclaration.solveType is deprecated
... and what to use now?

### PR DESCRIPTION
**Pull request by ftomassetti**
Adding comments to fix #1395 #1396 #1397

### CODE REVIEW

**Comment by matozoid** [comment]
There are lots of methods with these names, but only some are marked deprecated. Is it supposed to be that way?

**Comment by ftomassetti** [comment]
Most of those methods are in contexts classes, where I think it is fine to have them. I have deprecated one more method, which was used only for other deprecated methods. There is also a `solveType` in the `SymbolSolver` class but that one does not take a `TypeSolver` so it should be fine

**Comment by matozoid** [comment]
Thanks, +1 then.

**Comment by matozoid** [comment]
If this also helps #1910, do continue the chat there.

**Comment by MysterAitch** [comment]
Note that not all linked issues were automatically closed. Seems that GitHub is nitpicky about having "fixes" or similar immediately before every issue reference?

**Comment by matozoid** [comment]
Here's the doc: https://help.github.com/articles/closing-issues-using-keywords/ . I'll go close them.

**Pull request merged**
