### PR TITLE
[IDEA] Simple dockerfile for releasing

### PR DESCRIPTION
**Pull request by matozoid**
A simple Dockerfile that runs the release in a simple linux environment.

### CODE REVIEW

**Comment by MysterAitch** [comment]
Looks promising -- assuming that is a complete example, it's much more simple than I expected it to be! :) 

My previous experience is mostly with vagrant which spins up heavier virtual machines rather than more lightweight docker containers.

In terms of expansion / updates, might it be possible to set git ssh keys and other config stuff as environment variables? Or is that not really how it works?

**Comment by matozoid** [comment]
Docker is pretty good at interacting with the environment. The COPY action, for example, takes stuff that is on your normal file system and copies it into the virtual filesystem in Docker.

One improvement I haven't mentioned is that you can magically let your local .m2 repository appear in the container, so it won't spend five minutes downloading the world every time.

**Comment by MysterAitch** [comment]
To skip tests and do a non-interactive `release:prepare`:

```sh
mvn -e --batch-mode -Darguments="-DskipTests" release:clean release:prepare release:perform
```

To build and run the Dockerfile (run from the project root, with the dockerfile within the dev-files subdirectory). No idea if the build/run is the way it's supposed to be done, but it kinda works :P 

- Note the paths to the "volume"s will need to be configured locally. 
- Note the dockerfile will need git config details to be set (I had to do this in the dockerfile, which won't be sustainable if this is shared - is there a better way?)
- Note that there doesn't seem to be a way to do a `release:rollback` once the container closes (other than maybe manually creating the backup poms)

```sh
docker build --tag jpbuild:1.1 --file ./dev-files/docker_trigger_release/Dockerfile . 

docker run \
    -v /home/jp-docker/.m2:/root/.m2 \
    -v /home/jp-docker/.ssh:/root/.ssh \
    jpbuild:1.1
```

Thoughts/comments welcome :)

**Comment by matozoid** [comment]
- Docker can map your local filesystem to the Docker fs, so that's how you can make secret stuff available in the container
- Rollback, in my opinion, is nice when it works, but painful when things have already been pushed to origin. Might be easier to just skip to the next version number :-)

**Pull request closed without merging**
