### PR TITLE
Merge testing into core

### PR DESCRIPTION
**Pull request by matozoid**
Well, why not?

### CODE REVIEW

**Comment by HoldYourWaffle** [comment]
Suggestion: move the generated code to it's own seperate module. When I first started with this project this really confused me.
No idea how modules really work in maven, but I think it'd make sortof sense.

**Comment by matozoid** [comment]
@HoldYourWaffle - what was the confusion exactly? I don't know why the generated code would be confusing since users don't need to generate anything.

**Comment by ftomassetti** [comment]
Conflicts arising here. Nothing against doing this

**Comment by matozoid** [comment]
Doing this would destroy all the [testcase] PR's, so I'm closing it.

**Pull request closed without merging**
