### PR TITLE
Fix how Variable Declarators, Fields, and Enum constants are being represented

### LINKED ISSUE #1668: Resolving VariableDeclaration throws IllegalStateException
When trying to resolving the stringArray in the following example, JSS throws an `java.lang.IllegalStateException: com.github.javaparser.ast.expr.VariableDeclarationExpr`

Example:
```
public class X {
  public static void main(String[] args) {
    String s = "a,b,c,d,e";
    String[] stringArray = s.split(',');
  }
}
```

Stacktrace:
```
java.lang.IllegalStateException: com.github.javaparser.ast.expr.VariableDeclarationExpr

	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration.<init>(JavaParserFieldDeclaration.java:53)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:101)
	at com.github.javaparser.ast.body.VariableDeclarator.resolve(VariableDeclarator.java:279)
```

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1668 and a related issue with JavaParserFieldDeclaration still used to represent enum constants.

Inherited test case provided in #1669

### CODE REVIEW

**Comment by matozoid** [comment]
Can you improve the PR name?

**Comment by matozoid** [comment]
+1

**Comment by ftomassetti** [comment]
For some reasons the tests pass on JDK9 and they are running forever on JDK8...
screen shot 2018-08-10 at 10 12 03

**Comment by ftomassetti** [comment]
`The job exceeded the maximum time limit for jobs, and has been terminated.`

Restarting

**Comment by matozoid** [comment]
Maybe we should put some of the book money into renting a real CI cloud.

**Comment by ftomassetti** [comment]
That could be a good idea. However we would need to find something that does not require too much effort to be managed. Perhaps the paid version of Travis?

**Comment by matozoid** [comment]
@ftomassetti looks like the only paid thing at Travis is the enterprise self-hosted version?

Anyway, we should just improve the build times :-)

**Pull request merged**
