### PR TITLE
Remove "executable" bit from code files

### PR DESCRIPTION
**Pull request by icmdaf**
They serve no purpose, but I suspect seem to annoy a security lint.

Some code files have 755 permissions, others didn't, probably random depending on which OS was used to submit.

### CODE REVIEW

**Comment by icmdaf** [comment]
The check failures look like flakes, but I don't have permissions to rerun them.

**Comment by jlerbsc** [comment]
Why do you want to push this change? What is the problem you are trying to solve?

**Comment by jlerbsc** [comment]
The errors seem to be related to codecov

     [2022-11-17T17:17:57.875Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:] 
    (https://codecov.io/) Error: There was an error fetching the storage URL during POST: [40](https://github.com/javaparser/javaparser/actions/runs/3490304574/jobs/5841563430#step:7:41)4 - {'detail': 
    ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
    Error: Codecov: Failed to properly upload: The process '/Users/runner/work/_actions/codecov/codecov-action/v3.1.1/dist/codecov' failed with exit code 255

**Comment by icmdaf** [comment]
> Why

IIUC our organisation has a security linter that requires extra review when pulling executable files (to make sure we don't fetch harmful scripts). So it requires this extra review for the safe java files as well, in case someone makes them a shell script. Not setting them as executable removes this attack vector.

> The errors

Could you kick off a rerun of the failures? It looks like the coverage itself succeeded, just the upload failed due to some consistency issue?

Thanks :)

**Pull request merged**
