### PR TITLE
Fix containsKey, get, putAll and Equals of VisitorMap

### PR DESCRIPTION
**Pull request by lodart**
See #1065
There is still `putAll` to fix, but I don't know how to do that.

### CODE REVIEW

**Comment by matozoid** [comment]
So you fixed putall too? Well done :-) I might complain about a lack of unit tests, but it's not like I wrote a lot myself...

**Comment by lodart** [comment]
Here you go ! Tell me if I do anything wrong, I'm not used to work like that :)

**Comment by matozoid** [comment]
You're doing perfectly well, actually! Would you like to do some refactorings that I thought of?
- we don't need to pass `innerMap` in the constructor. It's no use outside the `VisitorMap`. Remove that parameter and just `new` a `HashMap` in the field declaration.
- that `innerMap` has been declared as a raw type. Maybe we can declare it `Map<EqualsHashcodeOverridingFacade, V>` or `Map<EqualsHashcodeOverridingFacade, ?>` to get rid of some casts?
- really every method that accesses `innerMap` passing a key should be fixed, so also `remove`.

**Comment by lodart** [comment]
Unfortunately, I can't make `remove` to work correctly, and I don't know why :/ Neither did I succeed removing the casts... I failed you master (branch, lol) !

**Comment by matozoid** [comment]
Well, that's for another day then :-) Thank you for your contribution!

**Pull request merged**
