### PR TITLE
Migrate tests to junit 5

### PR DESCRIPTION
**Pull request by signed**
This solves most of #1976.
As far as I know there is no junit5 version of jBehave.
All the other tests have been moved to junit5.

### CODE REVIEW

**Comment by ftomassetti** [comment]
We should really be careful that all the tests keep running in all modules which have tests

**Comment by ftomassetti** [comment]
In this PR the tests run are:
* 1463
* 11
* 928 / 825 (the tests are run twice and the number varies)

**Comment by ftomassetti** [comment]
In master we had the same tests running so from my point of view this seems ok

**Comment by matozoid** [comment]
Very cool, thank you very much @signed!

**Comment by signed** [comment]
The least I could do. I need the migration for other projects and I could not have done it without javaparser.

**Comment by matozoid** [comment]
For most users, the least they can do is nothing at all, so thank you anyway ;-)

**Pull request merged**
