### PR TITLE
Fix issue 1257 - Revise UnionType and ResolvedUnionType

### LINKED ISSUE #1257: Revise UnionType and ResolvedUnionType
* `UnionType.isReference()` should return true
* The costructor of ResolvedUnionType should take a list and not a collection because order is meaningful

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1257

### CODE REVIEW

**Comment by matozoid** [comment]
Is it okay if this waits a week?

**Comment by ftomassetti** [comment]
Yes

**Comment by matozoid** [comment]
+1 btw

**Comment by ftomassetti** [comment]
thanks!

**Comment by matozoid** [comment]
Yeah, the week delay was only for the release - sorry for not being clear :-)

**Pull request merged**
