### PR TITLE
Prepare next release (2.3.0? 3.0.0?)

### PR DESCRIPTION
**Pull request by ftomassetti**
- updated version number
- added a changelog

About the version number:
I would go for 2.3.0: I think we introduce compatibility breaking changes but we do not have enough change to move to 3.0.0 in my opinion. What do you think?

### CODE REVIEW

**Comment by SmiddyPence** [comment]
ironically up versioning it probably the one thing the release plugin does reliably for you ;-)

**Comment by ftomassetti** [comment]
right but the version was 2.2.3 while I think we should release 2.3.0. I was not sure if the plugin would ask me which version I wanted to release or just remove the "-SNAPSHOT" suffix and use the current version

**Comment by SmiddyPence** [comment]
It will, but depending on how many times you have to do it this may be quicker.  You can keep bashing enter your way :)

**Comment by JanBessai** [comment]
I've just built it locally and it worked fine for me :+1:

**Comment by ftomassetti** [comment]
This is been released: merging this PR because it contains the changes necessary to do the release and the changes from the maven release plugin

**Pull request merged**
