### PR TITLE
Add get(int i) shortcuts for list getters.

### LINKED ISSUE #524: Make shortcuts for list.get(i)
So many `getTypes().get(0)` in the tests. Why not have helper methods for every list: `getType(int i) { return getTypes().get(i); }`

(this needs the equivalent setType(i, ...) too)

### PR DESCRIPTION
**Pull request by qnnguyen**
Fixes #524 
Changed usages of old getters, found by grep -r "get[^)][^)]\*()\.get([^)][^)]\*)" \*

### CODE REVIEW

**Comment by qnnguyen** [comment]
Pretty big commit, but all basically the same change repeatedly.

**Comment by ftomassetti** [comment]
It makes life easier to the user but it also means more code to mantain :)

**Comment by DeepSnowNeeL** [comment]
Please do it with default methods in interfaces !! It will be a lot easier

**Comment by qnnguyen** [comment]
Good point! Sorry, bit rusty with Java :( I'll make the changes

**Comment by matozoid** [comment]
Thank you very much for the contribution!

This does the getters of #524, but there was a remark about setters too, therefore #524 stays open.

**Comment by matozoid** [comment]
Congratulations by the way, @qnnguyen, you are contributor number 40! :)

**Pull request merged**
